import {test,expect} from './runtime'
test('external search, independent paging and toolbar share only their owning runtime',async({page})=>{
  await page.goto('/?example=composition')
  const first=page.locator('[data-composed-table="assets.first"]'),second=page.locator('[data-composed-table="assets.second"]')
  await expect(first.locator('.bt__footer')).toContainText('共 31 条')
  await first.getByRole('button',{name:'下一页',exact:true}).click()
  await expect(first.locator('.bt__footer')).toContainText('第 2 / 4 页')
  await expect(second.locator('.bt__footer')).toContainText('第 1 / 4 页')
  await first.getByRole('textbox',{name:'设备名称'}).fill('设备 3')
  await first.getByRole('button',{name:'显示或隐藏搜索'}).click()
  await expect(first.getByRole('textbox',{name:'设备名称'})).toBeHidden()
  await expect(second.getByRole('textbox',{name:'设备名称'})).toBeVisible()
  await first.getByRole('button',{name:'显示或隐藏搜索'}).click()
  await expect(first.getByRole('textbox',{name:'设备名称'})).toHaveValue('设备 3')
  await first.getByRole('button',{name:'查询',exact:true}).click()
  await expect(first.locator('.bt__footer')).toContainText('共 3 条，第 1 / 1 页')
  await expect(first.getByRole('region',{name:'设备列表，可横向滚动'})).toContainText('设备 30')
  await expect(first.locator('.bt-search-summary')).toContainText('设备 3')
  await first.getByRole('button',{name:'重置',exact:true}).click()
  await first.getByRole('combobox',{name:'每页条数'}).selectOption('20')
  await expect(first.locator('.bt__footer')).toContainText('第 1 / 2 页')
  await page.setViewportSize({width:390,height:850})
  await expect(first.getByRole('button',{name:'下一页',exact:true})).toBeVisible()
})
