import {test,expect} from './runtime'

test('core-only entry never loads feature modules',async({page})=>{
  const featureRequests:string[]=[]
  page.on('request',request=>{if(/ColumnSettings|TableSearch|ViewSwitcher|TableToolbar|RowActions/.test(request.url()))featureRequests.push(request.url())})
  await page.goto('/?example=config&mode=core')
  await expect(page.locator('[data-business-table]')).toContainText('A-001')
  await expect(page.locator('.bt__bar')).toHaveCount(0)
  await expect(page.getByTestId('column-settings')).toHaveCount(0)
  expect(featureRequests).toEqual([])
})

test('settings are loaded on click and locked controls remain visible',async({page})=>{
  const settingsRequests:string[]=[]
  page.on('request',request=>{if(/ColumnSettings/.test(request.url()))settingsRequests.push(request.url())})
  await page.goto('/?example=config')
  await expect(page.locator('[data-business-table]')).toContainText('A-001')
  await expect(page.getByTestId('details-count')).toHaveText('设置详情读取次数：0')
  expect(settingsRequests).toEqual([])
  await page.getByTestId('column-settings').click()
  await expect(page.getByTestId('column-panel')).toBeVisible()
  await expect(page.getByRole('checkbox',{name:'显示编号',exact:true})).toBeChecked()
  await expect(page.getByRole('checkbox',{name:'显示编号',exact:true})).toBeDisabled()
  await expect(page.getByTitle('左冻结 编号',{exact:true})).toHaveAttribute('aria-pressed','true')
  await expect(page.getByTitle('左冻结 编号',{exact:true})).toBeDisabled()
  await page.getByRole('button',{name:'更多设置',exact:true}).click()
  await page.getByRole('button',{name:'编辑列 编号',exact:true}).click()
  const slider=page.getByRole('slider',{name:'编号列宽',exact:true})
  await expect(slider).toBeEnabled()
  await slider.fill('240');await slider.dispatchEvent('input')
  await expect(page.getByTestId('preference-delta')).toHaveCount(0)
  await page.getByRole('button',{name:'应用',exact:true}).click()
  await expect(page.getByTestId('preference-delta')).toContainText('"width": 240')
  await expect(page.getByTestId('preference-delta')).not.toContainText('"fixed"')
  await page.getByTestId('column-settings').click();await page.getByTestId('column-settings').click()
  await expect(page.getByTestId('details-count')).toHaveText('设置详情读取次数：1')
  expect(settingsRequests.length).toBeGreaterThan(0)
  await page.getByRole('button',{name:'模拟损坏的偏好'}).click()
  await expect(page.getByTestId('config-diagnostic')).toBeVisible()
  await expect(page.locator('[data-business-table]')).toContainText('A-001')
  await page.getByTestId('column-settings').click()
  await page.getByRole('button',{name:'查看',exact:true}).first().click()
  await expect(page.getByRole('status').filter({hasText:'查看 A-001'})).toBeVisible()
  await page.getByRole('button',{name:'更多操作 A-001',exact:true}).first().click()
  await expect(page.getByRole('menuitem',{name:'删除',exact:true})).toBeDisabled()
})

test('remote OFF bypasses settings details and module',async({page})=>{
  const requests:string[]=[]
  page.on('request',request=>{if(/ColumnSettings/.test(request.url()))requests.push(request.url())})
  await page.goto('/?example=config&mode=off')
  await expect(page.locator('[data-business-table]')).toContainText('A-001')
  await expect(page.getByTestId('column-settings')).toHaveCount(0)
  await expect(page.getByTestId('details-count')).toHaveText('设置详情读取次数：0')
  expect(requests).toEqual([])
})

test('custom and headless settings share guarded modification without default module',async({page})=>{
  const requests:string[]=[]
  page.on('request',request=>{if(/ColumnSettings/.test(request.url()))requests.push(request.url())})
  await page.goto('/?example=config&mode=custom')
  await page.getByTestId('column-settings').click()
  await expect(page.getByTestId('custom-settings')).toBeVisible()
  await expect(page.getByTestId('column-panel')).toHaveCount(0)
  await page.getByRole('button',{name:'调整编号列宽'}).click()
  await expect(page.getByTestId('preference-delta')).toContainText('"width": 240')
  await expect(page.getByTestId('preference-delta')).not.toContainText('"visible"')
  await page.getByRole('button',{name:'关闭',exact:true}).click()
  await expect(page.getByTestId('custom-settings')).toHaveCount(0)
  await page.goto('/?example=config&mode=headless')
  await expect(page.getByTestId('column-settings')).toHaveCount(0)
  await page.getByRole('button',{name:'读取列设置状态'}).click()
  await page.getByRole('button',{name:'调整编号列宽'}).click()
  await expect(page.getByTestId('preference-delta')).toContainText('"width": 240')
  await expect(page.getByTestId('column-panel')).toHaveCount(0)
  expect(requests).toEqual([])
})

test('narrow layouts keep settings buttons and width sliders usable',async({page})=>{
  await page.setViewportSize({width:390,height:900})
  await page.goto('/?example=config')
  const settings=page.getByTestId('column-settings')
  await expect(settings).toBeVisible()
  expect((await settings.boundingBox())!.height).toBeLessThanOrEqual(40)
  await settings.click()
  await page.getByRole('button',{name:'更多设置',exact:true}).click()
  await page.getByRole('button',{name:'编辑列 编号',exact:true}).click()
  const slider=page.getByRole('slider',{name:'编号列宽',exact:true})
  await expect(slider).toBeVisible()
  expect((await slider.boundingBox())!.width).toBeGreaterThan(200)
  await expect(page.getByRole('button',{name:'关闭表格设置'})).toBeInViewport()
  expect(await page.evaluate(()=>document.documentElement.scrollWidth)).toBeLessThanOrEqual(390)
})
