import { readFile } from 'node:fs/promises'
import { test, expect } from './runtime'
import type { Page } from '@playwright/test'

const rows = (page: Page) => page.locator('.vxe-table--main-wrapper .vxe-body--row')
async function open(page: Page, name: string) {
  await page.getByRole('button', { name: '数据工具', exact: true }).click()
  await expect(page.getByRole('menuitem', { name: '设置历史', exact: true })).toHaveCount(0)
  await page.getByRole('menuitem', { name, exact: true }).click()
  return page.getByRole('dialog', { name, exact: true })
}

test('grouping matches reference drawer, controls and expanded row geometry', async ({ page }, info) => {
  await page.setViewportSize({ width: 1280, height: 720 })
  await page.goto('http://127.0.0.1:4173/reference/legacy-v3.1/quotation-manager-v3.1/index.html')
  await page.getByRole('button', { name: '数据工具', exact: true }).click()
  await page.getByRole('menuitem', { name: '分组汇总', exact: true }).click()
  let dialog = page.getByRole('dialog', { name: '分组汇总', exact: true })
  await dialog.getByRole('button', { name: '展开全部', exact: true }).click()
  await expect(dialog).toHaveCSS('transform', 'none')
  const targets = [dialog, dialog.getByRole('combobox', { name: '第一分组', exact: true }), dialog.locator('summary').first(), dialog.locator('td').first()]
  const reference = await Promise.all(targets.map(target => target.boundingBox()))
  await info.attach('reference-grouping', { body: await dialog.screenshot(), contentType: 'image/png' })
  await page.goto('/'); dialog = await open(page, '分组汇总')
  await dialog.getByRole('button', { name: '展开全部', exact: true }).click()
  await expect(dialog).toHaveCSS('transform', 'none')
  const actual = await Promise.all([dialog, dialog.getByRole('combobox', { name: '第一分组', exact: true }), dialog.locator('summary').first(), dialog.locator('td').first()].map(target => target.boundingBox()))
  actual.forEach((box, index) => { for (const key of ['x','y','width','height'] as const) expect(Math.abs(box![key] - reference[index]![key]), `${index}.${key}`).toBeLessThanOrEqual(1) })
  await info.attach('vue-grouping', { body: await dialog.screenshot(), contentType: 'image/png' })
  await page.setViewportSize({ width: 390, height: 844 })
  await expect(dialog).toHaveCSS('width', '390px')
  await expect(dialog.getByRole('button', { name: '关闭', exact: true })).toBeInViewport()
})

test('row marking applies raw conditions, survives refresh and cancels drafts', async ({ page }, info) => {
  await page.goto('/'); await expect(rows(page)).toHaveCount(6)
  let dialog = await open(page, '条件标记')
  await expect(dialog).toHaveCSS('width', '1040px')
  await dialog.getByRole('button', { name: '添加规则', exact: true }).click()
  await dialog.getByRole('combobox', { name: '标记字段', exact: true }).selectOption('amount')
  await dialog.getByRole('combobox', { name: '筛选条件', exact: true }).selectOption('gte')
  await dialog.getByRole('textbox', { name: '筛选值', exact: true }).fill('200000')
  await dialog.getByRole('textbox', { name: '提示文字', exact: true }).fill('大额关注')
  await info.attach('conditional-rule', { body: await dialog.screenshot(), contentType: 'image/png' })
  await dialog.getByRole('button', { name: '应用标记', exact: true }).click()
  await expect(dialog).toHaveCount(0)
  await expect(rows(page).filter({ has: page.locator('.bt-row-mark') })).toHaveCount(3)
  await expect(rows(page)).toHaveCount(6)
  await page.reload(); await expect(rows(page).filter({ hasText: '大额关注' })).toHaveCount(3)
  dialog = await open(page, '条件标记')
  await dialog.getByRole('button', { name: '删除规则', exact: true }).click()
  await dialog.getByRole('button', { name: '取消', exact: true }).click()
  await expect(rows(page).filter({ hasText: '大额关注' })).toHaveCount(3)
})

test('grouping follows the complete query, expands nested details and exports exact totals', async ({ page }, info) => {
  await page.goto('/'); await expect(rows(page)).toHaveCount(6)
  const dialog = await open(page, '分组汇总')
  await expect(dialog).toContainText('完整查询结果 6 条')
  await expect(dialog.locator('.bt-report-group')).toHaveCount(4)
  await expect(dialog.locator('.bt-report-totals').first()).toContainText('376,510.00')
  await dialog.getByRole('combobox', { name: '第二分组', exact: true }).selectOption('status')
  await dialog.getByRole('button', { name: '展开全部', exact: true }).click()
  await expect(dialog.locator('.bt-report-group[open]')).toHaveCount(9)
  await expect(dialog.getByRole('cell', { name: 'Q20260914-0001', exact: true })).toBeVisible()
  await info.attach('grouping-expanded', { body: await dialog.screenshot(), contentType: 'image/png' })
  const download = page.waitForEvent('download')
  await dialog.getByRole('button', { name: '导出汇总', exact: true }).click()
  const file = await download
  expect(file.suggestedFilename()).toMatch(/\.xlsx$/)
  const bytes = await readFile((await file.path())!)
  expect(bytes.subarray(0, 2).toString()).toBe('PK')
  expect(bytes.toString('utf8')).toContain('<v>301310</v>')
  await dialog.getByRole('button', { name: '关闭', exact: true }).click()
  await expect(rows(page)).toHaveCount(6)
  await page.getByRole('combobox', { name: '客户', exact: true }).selectOption('澄川水务')
  await page.getByRole('button', { name: '查询', exact: true }).click()
  await expect(rows(page)).toHaveCount(3)
  await open(page, '分组汇总'); await expect(dialog).toContainText('完整查询结果 3 条')
  await expect(dialog.locator('.bt-report-group')).toHaveCount(1)
})

test('comparison keeps the query order, limits picks and exports baseline differences', async ({ page }, info) => {
  await page.setViewportSize({ width: 1280, height: 720 })
  await page.goto('http://127.0.0.1:4173/reference/legacy-v3.1/quotation-manager-v3.1/index.html')
  await page.getByRole('button', { name: '数据工具', exact: true }).click()
  await page.getByRole('menuitem', { name: '记录对比', exact: true }).click()
  const referenceDialog = page.getByRole('dialog', { name: '记录对比', exact: true })
  await referenceDialog.getByRole('checkbox', { name: 'Q20260914-0001 · 二期计量系统改造 · 001', exact: true }).check()
  await referenceDialog.getByRole('checkbox', { name: 'Q20260914-0181 · 化学品储罐监测 · 181', exact: true }).check()
  const referenceSearch = await referenceDialog.getByRole('searchbox').boundingBox()
  const referenceBase = await referenceDialog.getByRole('combobox', { name: '对比基准', exact: true }).boundingBox()
  await info.attach('reference-comparison', { body: await referenceDialog.screenshot(), contentType: 'image/png' })
  await page.goto('/'); await expect(rows(page)).toHaveCount(6)
  const dialog = await open(page, '记录对比')
  await dialog.locator('[data-report-pick="Q20260914-0181"]').check()
  await dialog.locator('[data-report-pick="Q20260914-0001"]').check()
  await expect(dialog.getByRole('combobox', { name: '对比基准', exact: true })).toHaveValue('Q20260914-0181')
  await dialog.getByRole('combobox', { name: '对比基准', exact: true }).selectOption('Q20260914-0001')
  const actualSearch = await dialog.getByRole('searchbox', { name: '搜索记录', exact: true }).boundingBox()
  const actualBase = await dialog.getByRole('combobox', { name: '对比基准', exact: true }).boundingBox()
  for (const key of ['x','y','width','height'] as const) {
    expect(Math.abs(actualSearch![key] - referenceSearch![key]), `search.${key}`).toBeLessThanOrEqual(1)
    expect(Math.abs(actualBase![key] - referenceBase![key]), `base.${key}`).toBeLessThanOrEqual(1)
  }
  await expect(dialog.locator('.bt-report-table')).toContainText('173,590.00')
  await dialog.getByRole('checkbox', { name: '只看不同项', exact: true }).check()
  await expect(dialog.getByRole('cell', { name: '负责人', exact: true })).toHaveCount(0)
  await dialog.locator('[data-report-pick="Q20260914-0121"]').check()
  await dialog.locator('[data-report-pick="Q20260912-0051"]').check()
  await expect(dialog.locator('[data-report-pick="Q20260912-0013"]')).toBeDisabled()
  await dialog.getByRole('combobox', { name: '对比基准', exact: true }).selectOption('Q20260914-0181')
  await expect(dialog.locator('.bt-report-table')).toContainText('-173,590.00')
  await dialog.getByRole('searchbox', { name: '搜索记录', exact: true }).fill('水厂')
  await expect(dialog.locator('[data-report-pick]')).toHaveCount(1)
  await expect(dialog.locator('.bt-report-table th')).toHaveCount(5)
  await info.attach('comparison', { body: await dialog.screenshot(), contentType: 'image/png' })
  const download = page.waitForEvent('download')
  await dialog.getByRole('button', { name: '导出对比', exact: true }).click()
  expect((await download).suggestedFilename()).toMatch(/\.xlsx$/)
  await dialog.getByRole('button', { name: '关闭', exact: true }).click()
  await expect(rows(page)).toHaveCount(6)
})

test('range selection supports pointer and keyboard, manual copy and query reset without hijacking links', async ({ page }, info) => {
  await page.addInitScript(() => Object.defineProperty(navigator, 'clipboard', { configurable: true, value: { writeText: async () => { throw new Error('denied') } } }))
  await page.goto('/'); await expect(rows(page)).toHaveCount(6)
  await open(page, '开启区域选择')
  const summary = page.locator('.bt-range-summary')
  await expect(summary).toContainText('区域选择已开启')
  await expect(summary.getByRole('button', { name: '退出', exact: true })).toHaveCSS('background-color', 'rgba(0, 0, 0, 0)')
  await expect(summary.getByRole('button', { name: '退出', exact: true })).toHaveCSS('color', 'rgb(36, 104, 232)')
  const cells = page.locator('.vxe-table--main-wrapper [data-range-column="amount"]')
  const from = await cells.nth(0).locator('xpath=ancestor::td').boundingBox(), to = await cells.nth(1).locator('xpath=ancestor::td').boundingBox()
  await page.mouse.move(from!.x + 2, from!.y + 2); await page.mouse.down()
  await page.mouse.move(to!.x + 2, to!.y + 2, { steps: 5 }); await page.mouse.up()
  await expect(summary).toContainText('当前页已选 2 个单元格')
  await expect(cells.nth(0).locator('xpath=ancestor::td')).toHaveCSS('background-color', 'rgb(241, 246, 255)')
  await expect(summary).toContainText('301,310.00')
  await page.keyboard.press('Shift+ArrowDown')
  await expect(summary).toContainText('当前页已选 3 个单元格')
  await expect(summary).toContainText('376,510.00')
  await page.keyboard.press('Control+c')
  const copy = page.getByRole('dialog', { name: '复制区域', exact: true })
  await expect(copy.getByRole('textbox', { name: '复制内容', exact: true })).toHaveValue('63,860.00\n237,450.00\n75,200.00')
  await copy.getByRole('button', { name: '关闭', exact: true }).click()
  await info.attach('range-selection', { body: await page.screenshot(), contentType: 'image/png' })
  await page.getByRole('button', { name: '刷新', exact: true }).click()
  await expect(summary).toContainText('区域选择已开启')
  await page.getByRole('button', { name: 'Q20260914-0001', exact: true }).click()
  await expect(page.getByRole('dialog', { name: '报价详情', exact: true })).toBeVisible()
  await page.getByRole('button', { name: '关闭报价详情', exact: true }).click()
  await summary.getByRole('button', { name: '退出', exact: true }).click(); await expect(summary).toHaveCount(0)
})

test('unconfigured, disabled and enabled data tools follow the declaration in generic demo', async ({ page }) => {
  await page.goto('/?example=config&mode=unconfigured')
  await expect(page.getByRole('button', { name: '数据工具', exact: true })).toHaveCount(0)
  await page.goto('/?example=config&mode=readonly')
  const dialog = await open(page, '条件标记')
  await expect(dialog.getByRole('button', { name: '添加规则', exact: true })).toBeDisabled()
  await expect(dialog.getByRole('button', { name: '应用标记', exact: true })).toHaveCount(0)
  await dialog.getByRole('button', { name: '关闭', exact: true }).click()
  await page.getByRole('button', { name: '数据工具', exact: true }).click()
  await expect(page.getByRole('menuitem', { name: '开启区域选择', exact: true })).toBeDisabled()
  await page.goto('/?example=config&mode=off')
  await expect(page.getByRole('button', { name: '数据工具', exact: true })).toHaveCount(0)
})
