import { test, expect } from './runtime'

test('demo keeps a stable content height and preserves column controls', async ({ page }) => {
  await page.setViewportSize({width:1920,height:945})
  await page.goto('/')
  const table = page.locator('[data-business-table]')
  await expect(table).toBeVisible()
  await expect(table.locator('.vxe-table--main-wrapper .vxe-body--row')).toHaveCount(6)
  await expect(table).toHaveClass(/bt--default/)
  await expect(page.getByRole('combobox', { name: '每页条数' })).toHaveValue('10')
  await expect(page.getByRole('button', { name: '批量操作', exact: true })).toHaveAttribute('aria-pressed', 'false')
  await expect(page.getByRole('button', { name: '展开', exact: true })).toBeVisible()
  await expect(table.getByText('Q20260914-0001',{exact:true}).first()).toBeVisible()
  await expect(page.getByRole('button', { name: '下一页' })).toBeDisabled()
  const height = () => table.evaluate(element => element.getBoundingClientRect().height)
  expect(await height()).toBeCloseTo(810,0)
  await page.getByRole('button', { name: '列设置', exact: true }).click()
  await expect(page.getByTestId('column-panel')).toBeVisible()
  const left = page.getByTitle('左冻结 有效期至')
  const right = page.getByTitle('右冻结 有效期至')
  await left.scrollIntoViewIfNeeded()
  // Like legacy, desktop freeze actions become interactive only on row hover/focus.
  const row = page.getByTestId('column-panel').locator('.bt-column-popup__row').filter({ has: page.getByRole('checkbox', { name: '显示有效期至', exact: true }) })
  await row.hover()
  await expect(row.locator('.bt-column-popup__pins')).toHaveCSS('opacity', '1')
  await expect(row.locator('.bt-column-popup__pins')).toHaveCSS('pointer-events', 'auto')
  await expect(left).toHaveAttribute('aria-pressed','false')
  await left.click()
  await expect(left).toHaveAttribute('aria-pressed','true')
  await right.click()
  await expect(right).toHaveAttribute('aria-pressed','true')
  await expect(left).toHaveAttribute('aria-pressed','false')
  await left.click()
  await expect(left).toHaveAttribute('aria-pressed','true')
  await expect(right).toHaveAttribute('aria-pressed','false')
  await page.getByRole('button',{name:'更多设置',exact:true}).click()
  await page.getByRole('button',{name:'编辑列 有效期至',exact:true}).click()
  await page.getByRole('slider', { name: '有效期至列宽' }).scrollIntoViewIfNeeded()
  await expect(page.getByRole('slider', { name: '有效期至列宽' })).toBeInViewport()
  await page.getByRole('button',{name:'应用',exact:true}).click()
  await expect(page.getByTestId('settings-drawer')).toHaveCount(0)
  await page.setViewportSize({width:900,height:945})
  await expect(table.locator('.vxe-table--fixed-left-wrapper').getByRole('button', { name: '有效期至列菜单', exact: true })).toBeVisible()
  await page.setViewportSize({width:1920,height:945})
  await page.evaluate(() => new Promise<void>(resolve => requestAnimationFrame(() => requestAnimationFrame(() => resolve()))))
  const settledHeight = await height()
  expect(settledHeight).toBeCloseTo(810,0)
  await page.evaluate(() => new Promise<void>(resolve => requestAnimationFrame(() => requestAnimationFrame(() => resolve()))))
  expect(await height()).toBeCloseTo(settledHeight, 0)
})
