import { test, expect } from './runtime'

test('demo keeps a stable content height and preserves column controls', async ({ page }) => {
  await page.goto('/')
  const table = page.locator('[data-business-table]')
  await expect(table).toBeVisible()
  await expect(page.locator('span:visible', { hasText: 'Q20260901-0001' }).first()).toBeVisible()
  await expect(page.getByRole('button', { name: '下一页' })).toBeDisabled()
  const height = () => table.evaluate(element => element.getBoundingClientRect().height)
  expect(await height()).toBeLessThan(700)
  await page.getByTestId('column-settings').click()
  await expect(page.getByTestId('column-panel')).toBeVisible()
  await page.getByRole('slider', { name: '有效期至列宽' }).scrollIntoViewIfNeeded()
  await expect(page.getByRole('slider', { name: '有效期至列宽' })).toBeInViewport()
  const left = page.getByTitle('左冻结 报价编号')
  const right = page.getByTitle('右冻结 报价编号')
  await expect(left).toHaveClass(/on/)
  await left.click()
  await expect(left).not.toHaveClass(/on/)
  await right.click()
  await expect(right).toHaveClass(/on/)
  await expect(left).not.toHaveClass(/on/)
  await left.click()
  await expect(left).toHaveClass(/on/)
  await expect(right).not.toHaveClass(/on/)
  await page.getByTestId('column-settings').click()
  await page.evaluate(() => new Promise<void>(resolve => requestAnimationFrame(() => requestAnimationFrame(() => resolve()))))
  const settledHeight = await height()
  expect(settledHeight).toBeLessThan(700)
  await page.evaluate(() => new Promise<void>(resolve => requestAnimationFrame(() => requestAnimationFrame(() => resolve()))))
  expect(await height()).toBeCloseTo(settledHeight, 0)
})
