import { test, expect } from './runtime'
import type { Page, Locator } from '@playwright/test'

const body = (page: Page) => page.locator('.vxe-table--main-wrapper .vxe-body--row')
async function openColumn(page: Page, id: string, name: string) {
  const button = page.locator('.vxe-table--main-wrapper').getByTestId(`column-filter-${id}`)
  await button.scrollIntoViewIfNeeded()
  // Lazy action columns can resize the header after hover; keyboard focus keeps
  // this accessible trigger revealed while the table finishes its layout.
  await button.focus()
  await expect(button).toBeFocused()
  await button.click()
  const dialog = page.getByRole('dialog', { name: `筛选 · ${name}`, exact: true })
  await expect(dialog).toBeVisible(); return dialog
}
async function setRule(row: Locator, field: string, operator: string, value?: string) {
  await row.getByRole('combobox', { name: '筛选字段', exact: true }).selectOption(field)
  await row.getByRole('combobox', { name: '筛选条件', exact: true }).selectOption(operator)
  if (value !== undefined) await row.getByRole('textbox', { name: '筛选值', exact: true }).fill(value)
}
async function openCombined(page: Page) {
  const tools = page.getByRole('button', { name: '数据工具', exact: true })
  await tools.click()
  await page.getByRole('menuitem', { name: '组合筛选', exact: true }).click()
  const dialog = page.getByRole('dialog', { name: '组合筛选', exact: true })
  await expect(dialog).toBeVisible()
  return dialog
}

test('combined drawer keeps the reference empty layout and condition card geometry', async ({ page }, info) => {
  await page.setViewportSize({ width: 1280, height: 720 })
  await page.goto('http://127.0.0.1:4173/reference/legacy-v3.1/quotation-manager-v3.1/index.html')
  await page.getByRole('button', { name: '数据工具', exact: true }).click()
  const legacyMenuWidth = (await page.getByRole('menu', { name: '数据工具', exact: true }).boundingBox())!.width
  await page.getByRole('menuitem', { name: '组合筛选', exact: true }).click()
  const reference = page.getByRole('dialog', { name: '组合筛选', exact: true })
  await expect(reference).toHaveCSS('transform', 'none')
  const legacyEmpty = await reference.locator('.settings-empty').boundingBox()
  const legacySelect = await reference.getByRole('combobox', { name: '组合方式', exact: true }).boundingBox()
  const legacyAdd = await reference.getByRole('button', { name: '添加条件', exact: true }).boundingBox()
  await info.attach('reference-combined-empty', { body: await reference.screenshot({ path: info.outputPath('reference-combined-empty.png') }), contentType: 'image/png' })
  await reference.getByRole('button', { name: '添加条件', exact: true }).click()
  const legacyCard = await reference.locator('.advanced-rule').first().boundingBox()
  await info.attach('reference-combined-card', { body: await reference.screenshot({ path: info.outputPath('reference-combined-card.png') }), contentType: 'image/png' })
  await reference.getByRole('textbox', { name: '筛选值', exact: true }).fill('Q20260914')
  await reference.getByRole('button', { name: '应用条件', exact: true }).click()
  const legacySummary = await page.locator('#filter-summary').boundingBox()
  const legacyChip = await page.locator('#filter-chips .filter-chip').boundingBox()
  await page.goto('/')
  await page.getByRole('button', { name: '数据工具', exact: true }).press('ArrowDown')
  await expect(page.getByRole('menuitem', { name: '组合筛选', exact: true })).toBeFocused()
  await expect(page.getByRole('menu', { name: '数据工具', exact: true })).toHaveCSS('width', `${legacyMenuWidth}px`)
  await page.getByRole('menuitem', { name: '组合筛选', exact: true }).press('Enter')
  const dialog = page.getByRole('dialog', { name: '组合筛选', exact: true })
  await expect(dialog).toHaveCSS('transform', 'none')
  const sameBox = async (target: Locator, expected: NonNullable<typeof legacyEmpty>) => {
    const actual = await target.boundingBox()
    for (const key of ['x', 'y', 'width', 'height'] as const) expect(Math.abs(actual![key] - expected[key]), key).toBeLessThanOrEqual(1)
  }
  await sameBox(dialog.locator('.bt-ui-empty'), legacyEmpty!)
  await sameBox(dialog.getByRole('combobox', { name: '组合方式', exact: true }), legacySelect!)
  await sameBox(dialog.getByRole('button', { name: '添加条件', exact: true }), legacyAdd!)
  await dialog.getByRole('button', { name: '添加条件', exact: true }).click()
  await sameBox(dialog.locator('.bt-filter-rule').first(), legacyCard!)
  await info.attach('vue-combined-card', { body: await dialog.screenshot({ path: info.outputPath('vue-combined-card.png') }), contentType: 'image/png' })
  await dialog.getByRole('textbox', { name: '筛选值', exact: true }).fill('Q20260914')
  await dialog.getByRole('button', { name: '应用条件', exact: true }).click()
  await expect(page.getByRole('button', { name: '组合条件 1 项', exact: true })).toBeVisible()
  await sameBox(page.locator('.bt-search-summary'), legacySummary!)
  await sameBox(page.locator('.bt-filter-chip'), legacyChip!)
  await info.attach('vue-combined-summary', { body: await page.locator('.bt-search-summary').screenshot({ path: info.outputPath('vue-combined-summary.png') }), contentType: 'image/png' })
})

test('quotation data tools match combination AND OR, cancel, summary and complete clearing', async ({ page }, info) => {
  await page.setViewportSize({ width: 1280, height: 720 }); await page.goto('/')
  await expect(body(page)).toHaveCount(6)
  let dialog = await openCombined(page)
  await expect(dialog).toHaveCSS('width', '580px')
  await expect(dialog.getByText('尚未添加条件', { exact: true })).toBeVisible()
  await info.attach('combined-empty', { body: await dialog.screenshot(), contentType: 'image/png' })
  await dialog.getByRole('button', { name: '添加条件', exact: true }).click()
  await setRule(dialog.locator('.bt-filter-rule').first(), 'amount', 'gte', '200000')
  await dialog.getByRole('button', { name: '添加条件', exact: true }).click()
  await setRule(dialog.locator('.bt-filter-rule').nth(1), 'status', 'in')
  await dialog.getByRole('checkbox', { name: '草稿', exact: true }).check()
  await info.attach('combined-rules', { body: await dialog.screenshot(), contentType: 'image/png' })
  await dialog.getByRole('button', { name: '应用条件', exact: true }).click()
  await expect(body(page)).toHaveCount(1)
  await expect(body(page).first()).toContainText('Q20260914-0181')
  const chip = page.getByRole('button', { name: '组合条件 2 项', exact: true })
  await expect(chip).toHaveAttribute('title', /200000.*且.*草稿/)
  await chip.click()
  dialog = page.getByRole('dialog', { name: '组合筛选', exact: true })
  await dialog.getByRole('combobox', { name: '组合方式', exact: true }).selectOption('or')
  await dialog.getByRole('button', { name: '取消', exact: true }).click()
  await expect(body(page)).toHaveCount(1)
  await chip.click()
  await expect(dialog.getByRole('combobox', { name: '组合方式', exact: true })).toHaveValue('and')
  await dialog.getByRole('combobox', { name: '组合方式', exact: true }).selectOption('or')
  await dialog.getByRole('button', { name: '应用条件', exact: true }).click()
  await expect(body(page)).toHaveCount(5)
  await page.getByLabel('客户', { exact: true }).selectOption('澄川水务')
  await page.getByRole('button', { name: '查询', exact: true }).click()
  await expect(body(page)).toHaveCount(2)
  const column = await openColumn(page, 'amount', '含税金额（元）')
  await column.getByRole('combobox', { name: '筛选条件', exact: true }).selectOption('gte')
  await column.getByRole('textbox', { name: '筛选值', exact: true }).fill('100000')
  await column.getByRole('button', { name: '应用筛选', exact: true }).click()
  await expect(body(page)).toHaveCount(1)
  const summary = page.locator('.bt-search-summary')
  await expect(summary).toHaveCount(1)
  await expect(summary.getByRole('button', { name: '清除条件', exact: true })).toHaveCount(1)
  await info.attach('combined-query-summary', { body: await summary.screenshot(), contentType: 'image/png' })
  await summary.getByRole('button', { name: '清除条件', exact: true }).click()
  await expect(body(page)).toHaveCount(6)
  await expect(summary).toHaveCount(0)
  await expect(page.getByLabel('客户', { exact: true })).toHaveValue('')
})

test('combination plans stay drafts and a view restores all query layers', async ({ page }) => {
  await page.setViewportSize({ width: 1440, height: 945 }); await page.goto('/')
  await page.getByLabel('客户', { exact: true }).selectOption('澄川水务')
  await page.getByRole('button', { name: '查询', exact: true }).click()
  const column = await openColumn(page, 'amount', '含税金额（元）')
  await column.getByRole('combobox', { name: '筛选条件', exact: true }).selectOption('gte')
  await column.getByRole('textbox', { name: '筛选值', exact: true }).fill('100000')
  await column.getByRole('button', { name: '应用筛选', exact: true }).click()
  let dialog = await openCombined(page)
  await dialog.getByRole('button', { name: '添加条件', exact: true }).click()
  await setRule(dialog.locator('.bt-filter-rule').first(), 'status', 'in')
  await dialog.getByRole('checkbox', { name: '草稿', exact: true }).check()
  await dialog.getByRole('button', { name: '筛选方案', exact: true }).click()
  const plans = page.getByRole('dialog', { name: '筛选方案', exact: true })
  await plans.getByRole('button', { name: '保存为方案', exact: true }).click()
  const name = page.getByRole('dialog', { name: '保存筛选方案', exact: true })
  await name.getByRole('textbox', { name: '方案名称', exact: true }).fill('草稿金额')
  await name.getByRole('button', { name: '保存', exact: true }).click()
  await expect(name).toHaveCount(0)
  await plans.getByRole('button', { name: '重命名', exact: true }).click()
  const rename = page.getByRole('dialog', { name: '重命名筛选方案', exact: true })
  await rename.getByRole('textbox', { name: '方案名称', exact: true }).fill('组合草稿')
  await rename.getByRole('button', { name: '保存', exact: true }).click()
  await plans.getByRole('button', { name: '关闭', exact: true }).click()
  await dialog.getByRole('button', { name: '取消', exact: true }).click()
  await expect(page.getByRole('button', { name: '组合条件 1 项', exact: true })).toHaveCount(0)
  dialog = await openCombined(page)
  await dialog.getByRole('button', { name: '筛选方案', exact: true }).click()
  await plans.getByRole('combobox', { name: '筛选方案', exact: true }).selectOption({ label: '组合草稿' })
  await expect(plans).toHaveCount(0)
  await dialog.getByRole('button', { name: '应用条件', exact: true }).click()
  await expect(page.getByRole('button', { name: '组合条件 1 项', exact: true })).toBeVisible()
  await page.getByRole('button', { name: '保存与切换视图' }).click()
  await page.getByRole('button', { name: '另存为视图', exact: true }).click()
  const view = page.getByRole('dialog', { name: '保存视图', exact: true })
  await view.getByRole('textbox', { name: /视图名称/ }).fill('三层筛选')
  await view.getByRole('button', { name: '保存', exact: true }).click()
  await page.reload(); await expect(body(page)).toHaveCount(6)
  await page.getByRole('button', { name: '保存与切换视图' }).click()
  await page.getByRole('button', { name: '三层筛选', exact: true }).click()
  await expect(body(page)).toHaveCount(1)
  await expect(page.locator('.bt-search-summary__chip')).toHaveCount(1)
  await expect(page.getByLabel('表格筛选条件').locator('.bt-filter-chip')).toHaveCount(2)
  await expect(page.locator('.q-modified')).toHaveCount(0)
  await page.getByRole('button', { name: '清除组合筛选', exact: true }).click()
  await expect(page.locator('.q-modified')).toBeVisible()
  await expect(body(page)).toHaveCount(1)
  dialog = await openCombined(page)
  await dialog.getByRole('button', { name: '筛选方案', exact: true }).click()
  await plans.getByRole('combobox', { name: '筛选方案', exact: true }).selectOption({ label: '组合草稿' })
  await dialog.getByRole('button', { name: '筛选方案', exact: true }).click()
  await plans.getByRole('button', { name: '删除方案', exact: true }).click()
  await page.getByRole('dialog', { name: '删除筛选方案', exact: true }).getByRole('button', { name: '删除', exact: true }).click()
  await expect(plans.getByRole('combobox', { name: '筛选方案', exact: true }).locator('option')).toHaveCount(1)
})

test('column filters remain separate from quotation search and cancel is non-mutating', async ({ page }, info) => {
  await page.setViewportSize({ width: 1920, height: 945 }); await page.goto('/')
  await expect(body(page)).toHaveCount(6)
  await page.getByLabel('客户', { exact: true }).selectOption('澄川水务')
  await page.getByRole('button', { name: '查询', exact: true }).click()
  await expect(body(page)).toHaveCount(3)
  let dialog = await openColumn(page, 'amount', '含税金额（元）')
  await expect(dialog).toHaveCSS('width', '480px')
  await dialog.getByRole('combobox', { name: '筛选条件' }).selectOption('gte')
  await dialog.getByRole('textbox', { name: '筛选值', exact: true }).fill('100000')
  await info.attach('column-filter', { body: await dialog.screenshot(), contentType: 'image/png' })
  await dialog.getByRole('button', { name: '取消', exact: true }).click()
  await expect(body(page)).toHaveCount(3)
  dialog = await openColumn(page, 'amount', '含税金额（元）')
  await dialog.getByRole('combobox', { name: '筛选条件' }).selectOption('gte')
  await dialog.getByRole('textbox', { name: '筛选值', exact: true }).fill('100000')
  await dialog.getByRole('button', { name: '应用筛选', exact: true }).click()
  await expect(body(page)).toHaveCount(1)
  await expect(page.getByLabel('表格筛选条件').getByRole('button', { name: /含税金额.*大于等于/ })).toBeVisible()
  await page.getByRole('button', { name: '清除含税金额（元）筛选', exact: true }).click()
  await expect(body(page)).toHaveCount(3)
  await expect(page.getByLabel('客户', { exact: true })).toHaveValue('澄川水务')
  await expect(page.locator('.bt-search-summary__chip')).toHaveText('客户：澄川水务')
})

test('nested AND OR conditions and saved plans survive a page reload', async ({ page }, info) => {
  await page.setViewportSize({ width: 1440, height: 1000 }); await page.goto('/?example=config')
  await page.getByTestId('combined-filter').click()
  let dialog = page.getByRole('dialog', { name: '组合筛选', exact: true })
  await expect(dialog).toHaveCSS('width', '580px')
  const root = dialog.locator('.bt-filter-group[data-depth="0"]')
  await root.locator(':scope > .bt-filter-add').getByRole('button', { name: '添加条件', exact: true }).click()
  await setRule(root.locator(':scope > .bt-filter-rule-list > .bt-filter-rule').first(), 'amount', 'gte', '2000')
  await root.locator(':scope > .bt-filter-add').getByRole('button', { name: '添加条件组', exact: true }).click()
  const nested = dialog.locator('.bt-filter-group[data-depth="1"]')
  await nested.getByRole('combobox', { name: '条件组组合方式' }).selectOption('or')
  await setRule(nested.locator(':scope > .bt-filter-rule-list > .bt-filter-rule').first(), 'status', 'eq', '已确认')
  await nested.locator(':scope > .bt-filter-add').getByRole('button', { name: '添加条件', exact: true }).click()
  await setRule(nested.locator(':scope > .bt-filter-rule-list > .bt-filter-rule').nth(1), 'name', 'contains', '转换器')
  await dialog.getByRole('button', { name: '筛选方案', exact: true }).click()
  const plans = page.getByRole('dialog', { name: '筛选方案', exact: true })
  await plans.getByRole('button', { name: '保存为方案', exact: true }).click()
  const name = page.getByRole('dialog', { name: '保存筛选方案', exact: true })
  await name.getByRole('textbox', { name: '方案名称' }).fill('金额与状态组合')
  await name.getByRole('button', { name: '保存', exact: true }).click()
  await expect(name).toHaveCount(0)
  await plans.getByRole('button', { name: '关闭', exact: true }).click()
  await info.attach('nested-filter', { body: await dialog.screenshot(), contentType: 'image/png' })
  await dialog.getByRole('button', { name: '应用条件', exact: true }).click()
  await expect(body(page)).toHaveCount(1)
  await expect(body(page).first()).toContainText('A-002')
  await page.reload(); await expect(body(page)).toHaveCount(2)
  await page.getByTestId('combined-filter').click()
  dialog = page.getByRole('dialog', { name: '组合筛选', exact: true })
  await dialog.getByRole('button', { name: '筛选方案', exact: true }).click()
  await page.getByRole('dialog', { name: '筛选方案', exact: true }).getByRole('combobox', { name: '筛选方案', exact: true }).selectOption({ label: '金额与状态组合' })
  await expect(dialog.locator('.bt-filter-group[data-depth="1"]')).toHaveCount(1)
  await dialog.getByRole('button', { name: '应用条件', exact: true }).click(); await expect(body(page)).toHaveCount(1)
  await expect(body(page).first()).toContainText('A-002')
  await page.getByRole('button', { name: '清除组合筛选', exact: true }).click(); await expect(body(page)).toHaveCount(2)
})

test('date range filters include both boundaries', async ({ page }) => {
  await page.goto('/')
  const dialog = await openColumn(page, 'date', '有效期至')
  await dialog.getByRole('combobox', { name: '筛选条件' }).selectOption('between')
  await dialog.getByLabel('开始 / 下限', { exact: true }).fill('2026-11-02')
  await dialog.getByLabel('结束 / 上限', { exact: true }).fill('2026-11-02')
  await dialog.getByRole('button', { name: '应用筛选' }).click(); await expect(body(page)).toHaveCount(2)
})

test('option search preserves checked values and uses full source counts', async ({ page }) => {
  await page.goto('/')
  const dialog = await openColumn(page, 'status', '状态')
  const draft = dialog.getByRole('checkbox', { name: '草稿', exact: true })
  await expect(draft).toBeVisible()
  await expect(draft.locator('xpath=..').locator('small')).toHaveText('3')
  await draft.check(); await dialog.getByRole('searchbox', { name: '搜索筛选项' }).fill('已')
  await expect(draft).toHaveCount(0)
  await dialog.getByRole('searchbox', { name: '搜索筛选项' }).fill(''); await expect(draft).toBeChecked()
  await dialog.getByRole('button', { name: '应用筛选' }).click(); await expect(body(page)).toHaveCount(3)
})

test('nested Escape restores focus and the drawer fits a narrow viewport', async ({ page }, info) => {
  await page.setViewportSize({ width: 390, height: 844 }); await page.goto('/?example=config')
  const trigger = page.getByTestId('combined-filter'); await trigger.click()
  const dialog = page.getByRole('dialog', { name: '组合筛选', exact: true })
  await dialog.getByRole('button', { name: '筛选方案', exact: true }).click()
  const plans = page.getByRole('dialog', { name: '筛选方案', exact: true })
  await plans.getByRole('button', { name: '保存为方案' }).click()
  const nested = page.getByRole('dialog', { name: '保存筛选方案', exact: true })
  await expect(nested.getByRole('textbox', { name: '方案名称' })).toBeFocused()
  await page.keyboard.press('Escape'); await expect(nested).toHaveCount(0); await expect(dialog).toBeVisible()
  await expect(plans.getByRole('button', { name: '保存为方案' })).toBeFocused()
  await page.keyboard.press('Escape'); await expect(plans).toHaveCount(0)
  await expect(dialog.getByRole('button', { name: '筛选方案', exact: true })).toBeFocused()
  expect(await dialog.evaluate(element => element.scrollWidth <= element.clientWidth + 1)).toBe(true)
  await info.attach('filter-narrow', { body: await page.screenshot(), contentType: 'image/png' })
  await page.keyboard.press('Escape'); await expect(dialog).toHaveCount(0); await expect(trigger).toBeFocused()
})

test('configured material tables use the same first-party filter without quotation handlers', async ({ page }) => {
  await page.goto('/?example=config')
  await expect(body(page)).toHaveCount(2)
  const dialog = await openColumn(page, 'name', '名称')
  await dialog.getByRole('textbox', { name: '筛选值', exact: true }).fill('传感器')
  await dialog.getByRole('button', { name: '应用筛选' }).click(); await expect(body(page)).toHaveCount(1)
  await expect(body(page).first()).toContainText('A-001')
})

test('disabled filters never import their UI and enabled filters load it only on interaction', async ({ page }) => {
  const modules: string[] = []
  page.on('request', request => { if (/FilterFeature|FilterGroupEditor|FilterOptions/.test(request.url())) modules.push(request.url()) })
  await page.goto('/?example=config&mode=off')
  await expect(page.getByTestId('combined-filter')).toHaveCount(0)
  await expect(page.locator('.bt__column-filter')).toHaveCount(0); expect(modules).toEqual([])
  await page.goto('/?example=config'); await expect(body(page)).toHaveCount(2); expect(modules).toEqual([])
  await page.getByTestId('combined-filter').click()
  await expect(page.getByRole('dialog', { name: '组合筛选', exact: true })).toBeVisible()
  expect(modules.length).toBeGreaterThan(0)
})


test('saving a view restores each filter layer after reload without duplicating query chips', async ({ page }) => {
  await page.goto('/')
  await page.getByLabel('客户', { exact: true }).selectOption('澄川水务')
  await page.getByRole('button', { name: '查询', exact: true }).click()
  const filter = await openColumn(page, 'amount', '含税金额（元）')
  await filter.getByRole('combobox', {name:'筛选条件'}).selectOption('gte')
  await filter.getByRole('textbox', {name:'筛选值',exact:true}).fill('100000')
  await filter.getByRole('button', {name:'应用筛选'}).click()
  await expect(body(page)).toHaveCount(1)
  await page.getByRole('button', {name:'保存与切换视图'}).click()
  await page.getByRole('button', {name:'另存为视图',exact:true}).click()
  const name = page.getByRole('dialog', {name:'保存视图',exact:true})
  await name.getByRole('textbox', {name:/视图名称/}).fill('金额筛选视图')
  await name.getByRole('button', {name:'保存',exact:true}).click()
  await page.reload(); await expect(body(page)).toHaveCount(6)
  await page.getByRole('button', {name:'保存与切换视图'}).click()
  await page.getByRole('button', {name:'金额筛选视图',exact:true}).click()
  await expect(body(page)).toHaveCount(1)
  await expect(page.locator('.q-modified')).toHaveCount(0)
  await expect(page.locator('.bt-search-summary__chip')).toHaveCount(1)
  await expect(page.getByLabel('表格筛选条件').locator('.bt-filter-chip')).toHaveCount(1)
  await page.getByRole('button', {name:'清除含税金额（元）筛选',exact:true}).click()
  await expect(body(page)).toHaveCount(3)
  await expect(page.locator('.q-modified')).toHaveCount(1)
})

test('ordinary column filters retain the reference layout and footer alignment', async ({ page }, info) => {
  await page.setViewportSize({ width: 1920, height: 945 }); await page.goto('/')
  const dialog = await openColumn(page, 'status', '状态')
  await expect(dialog).toHaveCSS('width', '480px')
  await expect(dialog.locator('.bt-dialog-header')).toHaveCSS('padding', '16px 24px')
  await expect(dialog.locator('.bt-dialog-footer')).toHaveCSS('padding', '12px 24px')
  await expect(dialog.locator('.bt-filter-option').first()).toHaveCSS('font-size', '14px')
  await expect(dialog.getByText('已选 0 项', { exact: true })).toHaveCount(0)
  const footer = dialog.locator('.bt-dialog-footer')
  const clear = dialog.getByRole('button', { name: '清除此列', exact: true })
  const footerBox = await footer.boundingBox(), clearBox = await clear.boundingBox()
  expect(clearBox!.x - footerBox!.x).toBeGreaterThan(200)
  await info.attach('column-filter-reference-layout', { body: await dialog.screenshot(), contentType: 'image/png' })
})
