import { test, expect } from './runtime'
import type { Page, Locator } from '@playwright/test'

const body = (page: Page) => page.locator('.vxe-table--main-wrapper .vxe-body--row')
async function openColumn(page: Page, id: string, name: string) {
  const button = page.locator('.vxe-table--main-wrapper').getByTestId(`column-filter-${id}`)
  await button.scrollIntoViewIfNeeded()
  // Lazy action columns can resize the header after hover; keyboard focus keeps
  // this accessible trigger revealed while the table finishes its layout.
  await button.focus()
  await expect(button).toBeFocused()
  await button.click()
  const dialog = page.getByRole('dialog', { name: `筛选 · ${name}`, exact: true })
  await expect(dialog).toBeVisible(); return dialog
}
async function setRule(row: Locator, field: string, operator: string, value?: string) {
  await row.getByRole('combobox', { name: '筛选字段', exact: true }).selectOption(field)
  await row.getByRole('combobox', { name: '筛选条件', exact: true }).selectOption(operator)
  if (value !== undefined) await row.getByRole('textbox', { name: '筛选值', exact: true }).fill(value)
}

test('column filters remain separate from quotation search and cancel is non-mutating', async ({ page }, info) => {
  await page.setViewportSize({ width: 1920, height: 945 }); await page.goto('/')
  await expect(body(page)).toHaveCount(6)
  await page.getByLabel('客户', { exact: true }).selectOption('澄川水务')
  await page.getByRole('button', { name: '查询', exact: true }).click()
  await expect(body(page)).toHaveCount(3)
  let dialog = await openColumn(page, 'amount', '含税金额（元）')
  await expect(dialog).toHaveCSS('width', '480px')
  await dialog.getByRole('combobox', { name: '筛选条件' }).selectOption('gte')
  await dialog.getByRole('textbox', { name: '筛选值', exact: true }).fill('100000')
  await info.attach('column-filter', { body: await dialog.screenshot(), contentType: 'image/png' })
  await dialog.getByRole('button', { name: '取消', exact: true }).click()
  await expect(body(page)).toHaveCount(3)
  dialog = await openColumn(page, 'amount', '含税金额（元）')
  await dialog.getByRole('combobox', { name: '筛选条件' }).selectOption('gte')
  await dialog.getByRole('textbox', { name: '筛选值', exact: true }).fill('100000')
  await dialog.getByRole('button', { name: '应用筛选', exact: true }).click()
  await expect(body(page)).toHaveCount(1)
  await expect(page.getByLabel('表格筛选条件').getByRole('button', { name: /含税金额.*大于等于/ })).toBeVisible()
  await page.getByRole('button', { name: '清除含税金额（元）筛选', exact: true }).click()
  await expect(body(page)).toHaveCount(3)
  await expect(page.getByLabel('客户', { exact: true })).toHaveValue('澄川水务')
  await expect(page.locator('.bt-search-summary__chip')).toHaveText('客户：澄川水务')
})

test('nested AND OR conditions and saved plans survive a page reload', async ({ page }, info) => {
  await page.setViewportSize({ width: 1440, height: 1000 }); await page.goto('/?example=config')
  await page.getByTestId('combined-filter').click()
  let dialog = page.getByRole('dialog', { name: '组合筛选', exact: true })
  await expect(dialog).toHaveCSS('width', '580px')
  const root = dialog.locator('.bt-filter-group[data-depth="0"]')
  await root.locator(':scope > .bt-filter-add').getByRole('button', { name: '添加条件', exact: true }).click()
  await setRule(root.locator(':scope > .bt-filter-rule-list > .bt-filter-rule').first(), 'amount', 'gte', '2000')
  await root.locator(':scope > .bt-filter-add').getByRole('button', { name: '添加条件组', exact: true }).click()
  const nested = dialog.locator('.bt-filter-group[data-depth="1"]')
  await nested.getByRole('combobox', { name: '条件组组合方式' }).selectOption('or')
  await setRule(nested.locator(':scope > .bt-filter-rule-list > .bt-filter-rule').first(), 'status', 'eq', '已确认')
  await nested.locator(':scope > .bt-filter-add').getByRole('button', { name: '添加条件', exact: true }).click()
  await setRule(nested.locator(':scope > .bt-filter-rule-list > .bt-filter-rule').nth(1), 'name', 'contains', '转换器')
  await dialog.getByRole('button', { name: '保存为方案', exact: true }).click()
  const name = page.getByRole('dialog', { name: '保存筛选方案', exact: true })
  await name.getByRole('textbox', { name: '方案名称' }).fill('金额与状态组合')
  await name.getByRole('button', { name: '保存', exact: true }).click()
  await expect(name).toHaveCount(0)
  await info.attach('nested-filter', { body: await dialog.screenshot(), contentType: 'image/png' })
  await dialog.getByRole('button', { name: '应用条件', exact: true }).click()
  await expect(body(page)).toHaveCount(1)
  await expect(body(page).first()).toContainText('A-002')
  await page.reload(); await expect(body(page)).toHaveCount(2)
  await page.getByTestId('combined-filter').click()
  dialog = page.getByRole('dialog', { name: '组合筛选', exact: true })
  await dialog.getByRole('combobox', { name: '筛选方案', exact: true }).selectOption({ label: '金额与状态组合' })
  await expect(dialog.locator('.bt-filter-group[data-depth="1"]')).toHaveCount(1)
  await dialog.getByRole('button', { name: '应用条件', exact: true }).click(); await expect(body(page)).toHaveCount(1)
  await expect(body(page).first()).toContainText('A-002')
  await page.getByRole('button', { name: '清除组合筛选', exact: true }).click(); await expect(body(page)).toHaveCount(2)
})

test('date range filters include both boundaries', async ({ page }) => {
  await page.goto('/')
  const dialog = await openColumn(page, 'date', '有效期至')
  await dialog.getByRole('combobox', { name: '筛选条件' }).selectOption('between')
  await dialog.getByLabel('开始 / 下限', { exact: true }).fill('2026-11-02')
  await dialog.getByLabel('结束 / 上限', { exact: true }).fill('2026-11-02')
  await dialog.getByRole('button', { name: '应用筛选' }).click(); await expect(body(page)).toHaveCount(2)
})

test('option search preserves checked values and uses full source counts', async ({ page }) => {
  await page.goto('/')
  const dialog = await openColumn(page, 'status', '状态')
  const draft = dialog.getByRole('checkbox', { name: '草稿', exact: true })
  await expect(draft).toBeVisible()
  await expect(draft.locator('xpath=..').locator('small')).toHaveText('3')
  await draft.check(); await dialog.getByRole('searchbox', { name: '搜索筛选项' }).fill('已')
  await expect(draft).toHaveCount(0)
  await dialog.getByRole('searchbox', { name: '搜索筛选项' }).fill(''); await expect(draft).toBeChecked()
  await dialog.getByRole('button', { name: '应用筛选' }).click(); await expect(body(page)).toHaveCount(3)
})

test('nested Escape restores focus and the drawer fits a narrow viewport', async ({ page }, info) => {
  await page.setViewportSize({ width: 390, height: 844 }); await page.goto('/?example=config')
  const trigger = page.getByTestId('combined-filter'); await trigger.click()
  const dialog = page.getByRole('dialog', { name: '组合筛选', exact: true })
  await dialog.getByRole('button', { name: '保存为方案' }).click()
  const nested = page.getByRole('dialog', { name: '保存筛选方案', exact: true })
  await expect(nested.getByRole('textbox', { name: '方案名称' })).toBeFocused()
  await page.keyboard.press('Escape'); await expect(nested).toHaveCount(0); await expect(dialog).toBeVisible()
  await expect(dialog.getByRole('button', { name: '保存为方案' })).toBeFocused()
  expect(await dialog.evaluate(element => element.scrollWidth <= element.clientWidth + 1)).toBe(true)
  await info.attach('filter-narrow', { body: await page.screenshot(), contentType: 'image/png' })
  await page.keyboard.press('Escape'); await expect(dialog).toHaveCount(0); await expect(trigger).toBeFocused()
})

test('configured material tables use the same first-party filter without quotation handlers', async ({ page }) => {
  await page.goto('/?example=config')
  await expect(body(page)).toHaveCount(2)
  const dialog = await openColumn(page, 'name', '名称')
  await dialog.getByRole('textbox', { name: '筛选值', exact: true }).fill('传感器')
  await dialog.getByRole('button', { name: '应用筛选' }).click(); await expect(body(page)).toHaveCount(1)
  await expect(body(page).first()).toContainText('A-001')
})

test('disabled filters never import their UI and enabled filters load it only on interaction', async ({ page }) => {
  const modules: string[] = []
  page.on('request', request => { if (/FilterFeature|FilterGroupEditor|FilterOptions/.test(request.url())) modules.push(request.url()) })
  await page.goto('/?example=config&mode=off')
  await expect(page.getByTestId('combined-filter')).toHaveCount(0)
  await expect(page.locator('.bt__column-filter')).toHaveCount(0); expect(modules).toEqual([])
  await page.goto('/?example=config'); await expect(body(page)).toHaveCount(2); expect(modules).toEqual([])
  await page.getByTestId('combined-filter').click()
  await expect(page.getByRole('dialog', { name: '组合筛选', exact: true })).toBeVisible()
  expect(modules.length).toBeGreaterThan(0)
})


test('saving a view restores each filter layer after reload without duplicating query chips', async ({ page }) => {
  await page.goto('/')
  await page.getByLabel('客户', { exact: true }).selectOption('澄川水务')
  await page.getByRole('button', { name: '查询', exact: true }).click()
  const filter = await openColumn(page, 'amount', '含税金额（元）')
  await filter.getByRole('combobox', {name:'筛选条件'}).selectOption('gte')
  await filter.getByRole('textbox', {name:'筛选值',exact:true}).fill('100000')
  await filter.getByRole('button', {name:'应用筛选'}).click()
  await expect(body(page)).toHaveCount(1)
  await page.getByRole('button', {name:'保存与切换视图'}).click()
  await page.getByRole('button', {name:'另存为视图',exact:true}).click()
  const name = page.getByRole('dialog', {name:'保存视图',exact:true})
  await name.getByRole('textbox', {name:/视图名称/}).fill('金额筛选视图')
  await name.getByRole('button', {name:'保存',exact:true}).click()
  await page.reload(); await expect(body(page)).toHaveCount(6)
  await page.getByRole('button', {name:'保存与切换视图'}).click()
  await page.getByRole('button', {name:'金额筛选视图',exact:true}).click()
  await expect(body(page)).toHaveCount(1)
  await expect(page.locator('.q-modified')).toHaveCount(0)
  await expect(page.locator('.bt-search-summary__chip')).toHaveCount(1)
  await expect(page.getByLabel('表格筛选条件').locator('.bt-filter-chip')).toHaveCount(1)
  await page.getByRole('button', {name:'清除含税金额（元）筛选',exact:true}).click()
  await expect(body(page)).toHaveCount(3)
  await expect(page.locator('.q-modified')).toHaveCount(1)
})

test('ordinary column filters retain the reference layout and footer alignment', async ({ page }, info) => {
  await page.setViewportSize({ width: 1920, height: 945 }); await page.goto('/')
  const dialog = await openColumn(page, 'status', '状态')
  await expect(dialog).toHaveCSS('width', '480px')
  await expect(dialog.locator('.bt-dialog-header')).toHaveCSS('padding', '16px 24px')
  await expect(dialog.locator('.bt-dialog-footer')).toHaveCSS('padding', '12px 24px')
  await expect(dialog.locator('.bt-filter-option').first()).toHaveCSS('font-size', '14px')
  await expect(dialog.getByText('已选 0 项', { exact: true })).toHaveCount(0)
  const footer = dialog.locator('.bt-dialog-footer')
  const clear = dialog.getByRole('button', { name: '清除此列', exact: true })
  const footerBox = await footer.boundingBox(), clearBox = await clear.boundingBox()
  expect(clearBox!.x - footerBox!.x).toBeGreaterThan(200)
  await info.attach('column-filter-reference-layout', { body: await dialog.screenshot(), contentType: 'image/png' })
})
