import { readFile } from 'node:fs/promises'
import { test, expect } from './runtime'

test('quotation drawer validates, preserves dirty input and persists create, edit and copy',async({page})=>{
  await page.goto('/')
  const rows=page.locator('.vxe-table--main-wrapper .vxe-body--row')
  await expect(rows).toHaveCount(6)
  await page.getByRole('button',{name:'新增报价',exact:true}).click()
  let dialog=page.getByRole('dialog',{name:'新增报价',exact:true})
  await expect(dialog).toHaveCSS('width','580px')
  await dialog.getByRole('button',{name:'保存报价',exact:true}).click()
  await expect(dialog.getByRole('alert')).toBeVisible()
  await dialog.getByRole('textbox',{name:'项目名称',exact:true}).fill('浏览器验收报价')
  await dialog.getByRole('button',{name:'取消',exact:true}).click()
  await page.getByRole('dialog',{name:'放弃修改？',exact:true}).getByRole('button',{name:'取消',exact:true}).click()
  await expect(dialog.getByRole('textbox',{name:'项目名称',exact:true})).toHaveValue('浏览器验收报价')
  await dialog.getByRole('combobox',{name:'客户',exact:true}).fill('验收客户')
  await dialog.getByRole('combobox',{name:'大区',exact:true}).selectOption('华东')
  await dialog.getByRole('textbox',{name:'含税金额（元）',exact:true}).fill('1234.56')
  await dialog.getByRole('button',{name:'保存报价',exact:true}).click()
  await expect(dialog).toHaveCount(0)
  await expect(rows).toHaveCount(7)
  await page.reload()
  const row=rows.filter({hasText:'浏览器验收报价'})
  await expect(row).toHaveCount(1)
  const id=await row.getAttribute('rowid')
  await page.locator(`.vxe-body--row[rowid="${id}"]`).getByRole('button',{name:'查看',exact:true}).click()
  dialog=page.getByRole('dialog',{name:'报价详情',exact:true})
  await expect(dialog).toContainText('1,234.56')
  await dialog.getByRole('button',{name:'修改报价',exact:true}).click()
  dialog=page.getByRole('dialog',{name:'修改报价',exact:true})
  await dialog.getByRole('textbox',{name:'项目名称',exact:true}).fill('修改后的验收报价')
  await dialog.getByRole('textbox',{name:'项目名称',exact:true}).press('Control+Enter')
  await expect(dialog).toHaveCount(0)
  const edited=page.locator(`.vxe-body--row[rowid="${id}"]`)
  await edited.getByRole('button',{name:/^更多操作 /}).click()
  await page.getByRole('menuitem',{name:'复制为草稿',exact:true}).click()
  const copy=page.getByRole('dialog',{name:'复制报价',exact:true})
  await expect(copy.getByRole('combobox',{name:'状态',exact:true})).toHaveValue('草稿')
  await copy.getByRole('button',{name:'保存报价',exact:true}).click()
  await expect(rows).toHaveCount(8)
  const stored=await page.evaluate(()=>JSON.parse(localStorage.getItem('business-table.quotation-demo.data.v1')!))
  expect(new Set(stored.rows.map((row:{id:string})=>row.id)).size).toBe(8)
})

test('export options and presets generate Excel, CSV and fixed templates',async({page})=>{
  await page.goto('/')
  await expect(page.locator('.vxe-table--main-wrapper .vxe-body--row')).toHaveCount(6)
  await page.getByRole('button',{name:'导出',exact:true}).click()
  let dialog=page.getByRole('dialog',{name:'导出报价',exact:true})
  await expect(dialog.getByRole('checkbox',{name:'导出备注',exact:true})).toBeVisible()
  await dialog.getByLabel('附加金额合计',{exact:true}).check()
  await dialog.getByRole('textbox',{name:'导出方案名称',exact:true}).fill('完整核对')
  await dialog.getByRole('button',{name:'保存方案',exact:true}).click()
  await expect(dialog.getByRole('status')).toHaveText('导出方案已保存。')
  await dialog.getByRole('button',{name:'预览',exact:true}).click()
  const preview=page.getByRole('dialog',{name:'导出预览',exact:true})
  await expect(preview).toContainText('Q20260914-0001')
  await preview.getByRole('button',{name:'关闭',exact:true}).click()
  const excel=page.waitForEvent('download')
  await dialog.getByRole('button',{name:'导出 Excel',exact:true}).click()
  const xlsx=await excel
  expect(xlsx.suggestedFilename()).toMatch(/\.xlsx$/)
  const data=await readFile((await xlsx.path())!)
  expect(data.subarray(0,2).toString()).toBe('PK')
  await page.reload()
  await page.getByRole('button',{name:'导出',exact:true}).click()
  dialog=page.getByRole('dialog',{name:'导出报价',exact:true})
  const preset=dialog.getByRole('combobox',{name:'已保存的导出方案',exact:true})
  await preset.selectOption({label:'完整核对'})
  await expect(dialog.getByLabel('附加金额合计',{exact:true})).toBeChecked()
  await dialog.getByRole('combobox',{name:'文件格式',exact:true}).selectOption('csv')
  const csvPromise=page.waitForEvent('download')
  await dialog.getByRole('button',{name:'导出 CSV',exact:true}).click()
  const csv=await csvPromise
  const text=await readFile((await csv.path())!,'utf8')
  expect(text).toContain('Q20260914-0001')
  expect(text).toContain('项目名称')
  expect(text).toContain('1,026,450.00')
  await page.getByRole('button',{name:'模板下载',exact:true}).click()
  const template=page.getByRole('dialog',{name:'模板下载',exact:true})
  await expect(template).toContainText('不受个人列名称')
  const templatePromise=page.waitForEvent('download')
  await template.getByRole('button',{name:'空白模板',exact:true}).click()
  expect((await templatePromise).suggestedFilename()).toMatch(/空白\.xlsx$/)
})

test('batch selection replaces title and computes only the selected total',async({page})=>{
  await page.goto('/')
  await expect(page.locator('.vxe-table--main-wrapper .vxe-body--row')).toHaveCount(6)
  await page.getByRole('button',{name:'批量操作',exact:true}).click()
  await page.getByRole('checkbox',{name:'选择 Q20260914-0001',exact:true}).first().check()
  await expect(page.getByRole('button',{name:'保存与切换视图',exact:true})).toHaveCount(0)
  await expect(page.locator('.q-result-summary')).toContainText('所选合计¥ 63,860.00')
  await page.getByRole('button',{name:'选择全部 6 条',exact:true}).click()
  await expect(page.locator('.q-selection')).toContainText('已选 6 条')
  await expect(page.locator('.q-result-summary')).toContainText('所选合计¥ 1,026,450.00')
  await page.getByRole('button',{name:'导出所选',exact:true}).click()
  await expect(page.getByRole('radio',{name:'选中的报价（6 条）',exact:true})).toBeChecked()
  await page.getByRole('dialog',{name:'导出报价',exact:true}).getByRole('button',{name:'取消',exact:true}).click()
  await page.getByRole('button',{name:'取消选择',exact:true}).click()
  await expect(page.getByRole('button',{name:'保存与切换视图',exact:true})).toBeVisible()
})

test('query workspace preferences survive reload and slash focuses the hidden search',async({page})=>{
  await page.goto('/')
  await expect(page.locator('.vxe-table--main-wrapper .vxe-body--row')).toHaveCount(6)
  await page.getByRole('button',{name:'展开',exact:true}).click()
  await page.getByRole('button',{name:'查询条件',exact:true}).click()
  await expect(page.getByRole('searchbox',{name:'关键词',exact:true})).toHaveCount(0)
  await page.keyboard.press('/')
  await expect(page.getByRole('searchbox',{name:'关键词',exact:true})).toBeFocused()
  await page.getByRole('button',{name:'批量操作',exact:true}).click()
  await page.reload()
  await expect(page.getByRole('button',{name:'收起',exact:true})).toBeVisible()
  await expect(page.getByRole('button',{name:'批量操作',exact:true})).toHaveAttribute('aria-pressed','false')
})

test('a view can update appearance, page size and query expansion without changing any filter',async({page})=>{
  await page.goto('/')
  await expect(page.locator('.vxe-table--main-wrapper .vxe-body--row')).toHaveCount(6)
  const views=page.getByRole('button',{name:'保存与切换视图',exact:true})
  await views.click()
  await page.getByRole('dialog',{name:'我的视图',exact:true}).getByRole('button',{name:'澄川水务专属',exact:true}).click()
  await page.getByRole('button',{name:'行高密度',exact:true}).click()
  await page.getByRole('menuitemradio',{name:'紧凑',exact:true}).click()
  await page.getByRole('combobox',{name:'每页条数'}).selectOption('25')
  await page.getByRole('button',{name:'展开',exact:true}).click()
  await expect(page.locator('.q-modified')).toHaveText('未保存')
  await views.click()
  await page.getByRole('button',{name:'更新当前视图',exact:true}).click()
  await page.getByRole('dialog',{name:'更新视图',exact:true}).getByRole('button',{name:'更新视图',exact:true}).click()
  await expect(page.locator('.q-modified')).toHaveCount(0)
  await views.click()
  await page.getByTitle('设为默认 澄川水务专属',{exact:true}).click()
  await page.reload()
  await expect(page.locator('[data-business-table]')).toHaveClass(/bt--compact/)
  await expect(page.getByRole('combobox',{name:'每页条数'})).toHaveValue('25')
  await expect(page.getByRole('button',{name:'收起',exact:true})).toBeVisible()
  await expect(page.locator('.q-modified')).toHaveCount(0)
})
