import { test, expect } from './runtime'

test('narrow tables keep project data readable and restore desktop frozen columns', async ({ page }, info) => {
  await page.setViewportSize({ width: 390, height: 900 })
  await page.goto('/')
  const table = page.locator('[data-business-table]')
  await expect(table.locator('.vxe-table--main-wrapper .vxe-body--row')).toHaveCount(3)
  const fixed = table.locator('.vxe-table--fixed-left-wrapper:visible, .vxe-table--fixed-right-wrapper:visible')
  await expect(fixed, 'mobile must not be covered by fixed ID and action overlays').toHaveCount(0)
  const name = table.locator('.vxe-table--main-wrapper .q-project-cell').first()
  await name.scrollIntoViewIfNeeded()
  expect(await name.evaluate(element => {
    const box = element.getBoundingClientRect()
    const x = Math.max(18, box.left + 8), y = box.top + Math.min(12, box.height / 2)
    const target = document.elementFromPoint(x, y)
    return !!target && element.contains(target)
  }), 'project text must receive pointer events, not an overlapping fixed column').toBe(true)
  await page.screenshot({ path: info.outputPath('readable-mobile-390.png'), fullPage: true })
  const body = table.locator('.vxe-table--main-wrapper .vxe-table--body-inner-wrapper')
  expect(await body.evaluate(element => element.scrollWidth > element.clientWidth)).toBe(true)
  await body.evaluate(element => { element.scrollLeft = element.scrollWidth })
  await table.getByRole('button', { name: '更多操作 Q20260914-0181', exact: true }).first().click()
  await expect(page.getByRole('menu').getByRole('menuitem', { name: '删除', exact: true })).toBeInViewport()
  await page.keyboard.press('Escape')
  // A wide container that still overflows makes VXE's fixed overlays observable.
  await page.setViewportSize({ width: 900, height: 900 })
  await expect(fixed).toHaveCount(2)
  await page.getByTestId('column-settings').click()
  await expect(page.getByTestId('column-panel').getByTitle('左冻结 报价编号', { exact: true })).toHaveAttribute('aria-pressed', 'true')
})
