import { test, expect } from './runtime'

test('slow Provider reports loading and ignores an obsolete response', async ({ page }) => {
  await page.goto('/tests/e2e/fixtures/provider.html')
  const table = page.locator('[data-business-table]')
  await expect(table).toHaveAttribute('aria-busy', 'true')
  await expect(page.getByRole('status', { name: '加载中' })).toBeVisible()
  await page.getByPlaceholder('搜索当前数据').fill('new')
  await page.getByRole('button', { name: '查询', exact: true }).click()
  await expect.poll(() => page.evaluate(() => window.queryRequests.length)).toBe(2)
  expect(await page.evaluate(() => window.queryRequests[0].query.signal?.aborted)).toBe(true)
  await page.evaluate(() => window.queryRequests[1].resolve({ rows: [{ id: 'new-row' }], total: 1 }))
  await expect(page.getByText('new-row', { exact: true })).toBeVisible()
  await expect(table).toHaveAttribute('aria-busy', 'false')
  await expect(page.getByRole('status', { name: '加载中' })).toHaveCount(0)
  await page.evaluate(() => window.queryRequests[0].resolve({ rows: [{ id: 'old-row' }], total: 99 }))
  await expect(page.getByText('old-row', { exact: true })).toHaveCount(0)
  await expect(page.getByText('共 1 条，第 1 / 1 页')).toBeVisible()
})

test('a failed refresh keeps rows and can be retried without browser errors', async ({ page }) => {
  await page.goto('/tests/e2e/fixtures/provider.html')
  await expect.poll(() => page.evaluate(() => window.queryRequests.length)).toBe(1)
  await page.evaluate(() => window.queryRequests[0].resolve({ rows: [{ id: 'saved-row' }], total: 1 }))
  await expect(page.getByText('saved-row', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: '刷新', exact: true }).click()
  await expect.poll(() => page.evaluate(() => window.queryRequests.length)).toBe(2)
  await page.evaluate(() => window.queryRequests[1].reject(new Error('暂时无法读取数据')))
  await expect(page.getByRole('alert')).toHaveText('暂时无法读取数据')
  await expect(page.getByText('saved-row', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: '刷新', exact: true }).click()
  await expect.poll(() => page.evaluate(() => window.queryRequests.length)).toBe(3)
  await page.evaluate(() => window.queryRequests[2].resolve({ rows: [{ id: 'recovered-row' }], total: 1 }))
  await expect(page.getByRole('alert')).toHaveCount(0)
  await expect(page.getByText('recovered-row', { exact: true })).toBeVisible()
})
