import {test,expect} from './runtime'

async function openSettings(page:import('@playwright/test').Page){
  await page.goto('/')
  await page.getByRole('button',{name:'表格设置',exact:true}).click()
  return page.getByTestId('settings-drawer')
}

test('font search and palette change the same draft and apply to the live header',async({page},info)=>{
  await page.setViewportSize({width:1920,height:945})
  const drawer=await openSettings(page)
  await expect(drawer.getByRole('button',{name:'查找表头文字字体',exact:true})).toBeVisible()
  await drawer.getByRole('button',{name:'查找表头文字字体',exact:true}).click()
  const fontDialog=page.getByRole('dialog',{name:'选择字体',exact:true})
  await expect(fontDialog).toBeVisible()
  expect((await fontDialog.boundingBox())!.width).toBe(480)
  // The legacy font dialog must not inherit the surrounding form's padding.
  await expect(fontDialog.getByRole('searchbox')).toHaveCSS('padding-top','0px')
  await expect(fontDialog.getByRole('searchbox')).toHaveCSS('color','rgb(38, 50, 72)')
  await expect(fontDialog.getByRole('button',{name:'关闭字体选择',exact:true})).toHaveCSS('height','32px')
  await expect(fontDialog).toHaveCSS('font-synthesis','none')
  await expect(fontDialog.getByRole('searchbox',{name:'搜索字体'})).toBeFocused()
  await fontDialog.getByRole('searchbox').fill('雅黑')
  await expect(fontDialog.getByRole('option')).toHaveCount(1)
  await info.attach('font-search',{body:await page.screenshot(),contentType:'image/png'})
  await page.keyboard.press('ArrowDown')
  await page.keyboard.press('Enter')
  await expect(fontDialog).toHaveCount(0)
  await expect(drawer.getByRole('combobox',{name:'表头文字字体',exact:true})).toBeFocused()
  const color=drawer.locator('[data-color-picker="表头文字"]')
  await expect(color.getByRole('textbox',{name:'表头文字文字颜色',exact:true})).toHaveValue('')
  await color.locator('summary').click()
  await color.getByRole('button',{name:'使用深蓝色',exact:true}).click()
  const header=page.locator('.vxe-table--main-wrapper .vxe-header--column').filter({hasText:'项目名称 / 客户'}).locator('.bt__sort')
  const previous=await header.evaluate(el=>getComputedStyle(el).color)
  expect(previous).not.toBe('rgb(36, 104, 232)')
  await drawer.getByRole('button',{name:'应用',exact:true}).click()
  await expect(header).toHaveCSS('color','rgb(36, 104, 232)')
  await expect(header).toHaveCSS('font-family',/Microsoft YaHei/)
})

test('invalid color remains editable across columns and cannot be silently applied',async({page})=>{
  const drawer=await openSettings(page)
  await drawer.getByRole('textbox',{name:'显示名称',exact:true}).fill('待确认名称')
  const input=drawer.getByRole('textbox',{name:'表头文字文字颜色',exact:true})
  await input.fill('#oops')
  await expect(input).toHaveAttribute('aria-invalid','true')
  await expect(drawer.getByRole('button',{name:'应用',exact:true})).toBeDisabled()
  await drawer.getByRole('button',{name:'编辑列 负责人',exact:true}).click()
  await expect(drawer.getByRole('button',{name:'应用',exact:true})).toBeDisabled()
  await drawer.getByRole('button',{name:'定位颜色错误',exact:true}).click()
  await expect(input).toHaveValue('#oops')
  await expect(input).toBeFocused()
  await input.fill('#167457')
  await expect(drawer.getByRole('button',{name:'应用',exact:true})).toBeEnabled()
  await drawer.getByRole('button',{name:'取消',exact:true}).click()
  await expect(page.locator('.vxe-table--main-wrapper .vxe-header--column').filter({hasText:'待确认名称'})).toHaveCount(0)
})

test('nested Escape and alignment keys retain the editor instead of dismissing it',async({page})=>{
  const drawer=await openSettings(page)
  const trigger=drawer.getByRole('button',{name:'查找表头文字字体',exact:true})
  await expect(trigger).toBeVisible()
  await trigger.click()
  await page.getByRole('searchbox',{name:'搜索字体'}).fill('找不到')
  await expect(page.getByText('没有匹配的字体',{exact:true})).toBeVisible()
  await page.keyboard.press('Escape')
  await expect(drawer).toBeVisible()
  await expect(page.getByRole('dialog',{name:'选择字体',exact:true})).toHaveCount(0)
  const palette=drawer.locator('[data-color-picker="表头文字"] summary')
  await palette.click()
  await page.keyboard.press('Escape')
  await expect(palette).toBeFocused()
  await expect(drawer).toBeVisible()
  const initial=drawer.getByRole('button',{name:'表头文字默认对齐',exact:true})
  await initial.focus();await page.keyboard.press('ArrowRight')
  const left=drawer.getByRole('button',{name:'表头文字左对齐',exact:true})
  await expect(left).toBeFocused();await expect(left).toHaveAttribute('aria-pressed','true')
  await page.keyboard.press('End')
  await expect(drawer.getByRole('button',{name:'表头文字右对齐',exact:true})).toBeFocused()
})

test('quick hidden columns have the legacy strike-through and hidden pins do not catch clicks',async({page})=>{
  await page.goto('/');await page.getByRole('button',{name:'列设置',exact:true}).click()
  const panel=page.getByTestId('column-panel')
  const hidden=panel.locator('.bt-column-popup__row').filter({has:page.getByRole('checkbox',{name:'显示客户',exact:true})})
  await expect(hidden.locator('.bt-column-popup__name')).toHaveCSS('text-decoration-line','line-through')
  const ordinary=panel.locator('.bt-column-popup__row').filter({has:page.getByRole('checkbox',{name:'显示负责人',exact:true})})
  await page.mouse.move(0,0)
  await expect(ordinary.locator('.bt-column-popup__pins')).toHaveCSS('pointer-events','none')
  await ordinary.hover()
  await expect(ordinary.locator('.bt-column-popup__pins')).toHaveCSS('pointer-events','auto')
})

test('column context stays visible while scrolling settings content',async({page},info)=>{
  await page.setViewportSize({width:1920,height:945})
  const drawer=await openSettings(page)
  const detail=drawer.locator('.bt-settings-detail')
  const header=drawer.locator('.bt-settings-editor-header')
  const before=await header.boundingBox()
  await detail.evaluate(el=>{el.scrollTop=el.scrollHeight})
  await expect.poll(async()=>Math.abs((await header.boundingBox())!.y-before!.y)).toBeLessThanOrEqual(1)
  const context=drawer.locator('.bt-settings-detail__heading')
  const panelBox=await drawer.locator('.bt-settings-editor').boundingBox(),headingBox=await context.boundingBox()
  expect(headingBox!.y).toBeGreaterThanOrEqual(panelBox!.y-1)
  await expect(context).toBeInViewport()
  await info.attach('scrolled-settings',{body:await page.screenshot(),contentType:'image/png'})
})

test('all column sections collapse without losing drafts and navigation expands its destination',async({page})=>{
  const drawer=await openSettings(page)
  const name=drawer.getByRole('textbox',{name:'显示名称',exact:true})
  await name.fill('未应用的列名称')
  await drawer.getByRole('button',{name:'收起基本',exact:true}).click()
  await expect(name).toBeHidden()
  await drawer.getByRole('navigation',{name:'列设置内容'}).getByRole('button',{name:'基本',exact:true}).click()
  await expect(name).toBeVisible()
  await expect(name).toHaveValue('未应用的列名称')
  for(const title of ['表头文字','单元格文字','内容显示','列筛选','值映射','富文本显示模板','规则试算']){
    await drawer.getByRole('button',{name:'收起'+title,exact:true}).click()
    await expect(drawer.getByRole('button',{name:'展开'+title,exact:true})).toHaveAttribute('aria-expanded','false')
  }
  await drawer.getByRole('navigation',{name:'列设置内容'}).getByRole('button',{name:'筛选',exact:true}).click()
  await expect(drawer.getByRole('checkbox',{name:'允许列筛选',exact:true})).toBeInViewport()
  await expect(drawer.getByRole('button',{name:'收起列筛选',exact:true})).toHaveAttribute('aria-expanded','true')
  await drawer.getByRole('button',{name:'取消',exact:true}).click()
  await expect(page.locator('[data-business-table]')).not.toContainText('未应用的列名称')
})

test('quick column drag indicates the insertion edge and does not apply the draft until confirmed',async({page})=>{
  await page.goto('/');await page.getByRole('button',{name:'列设置',exact:true}).click()
  const panel=page.getByTestId('column-panel'),rows=panel.locator('.bt-column-popup__row')
  const source=panel.getByRole('button',{name:'拖动排序 状态',exact:true})
  const target=rows.filter({has:page.getByRole('checkbox',{name:'显示项目名称 / 客户',exact:true})})
  const handle=(await source.boundingBox())!
  await page.mouse.move(handle.x+handle.width/2,handle.y+handle.height/2)
  await page.mouse.down()
  await page.mouse.move(handle.x+handle.width/2+6,handle.y+handle.height/2,{steps:3})
  const box=(await target.boundingBox())!
  await page.mouse.move(box.x+box.width/2,box.y+2,{steps:5})
  await page.mouse.move(box.x+box.width/2+1,box.y+2)
  await expect(target).toHaveAttribute('data-reorder-edge','before')
  await expect(target).toHaveCSS('position','relative')
  expect(await target.evaluate(el=>getComputedStyle(el,'::after').height)).toBe('2px')
  await page.mouse.up()
  await expect(panel.locator('[data-reorder-edge]')).toHaveCount(0)
  const names=await rows.locator('.bt-column-popup__name').allTextContents()
  expect(names.slice(0,3)).toEqual(['报价编号','状态','项目名称 / 客户'])
  await panel.getByRole('button',{name:'取消',exact:true}).click()
  const headers=page.locator('.vxe-table--main-wrapper .vxe-header--column')
  expect((await headers.allTextContents()).join('')).toMatch(/项目名称.*状态/)
})

test('toolbar and action settings collapse by level while preserving edited values',async({page})=>{
  const drawer=await openSettings(page)
  await drawer.getByRole('tab',{name:'工具栏',exact:true}).click()
  const tool=drawer.getByRole('textbox',{name:'模板下载工具名称',exact:true})
  await tool.fill('下载模板草稿')
  await drawer.getByRole('button',{name:'收起页面工具栏',exact:true}).click()
  await expect(tool).toBeHidden()
  await expect(drawer.getByRole('textbox',{name:'刷新工具名称',exact:true})).toBeVisible()
  await drawer.getByRole('button',{name:'展开页面工具栏',exact:true}).click()
  await expect(tool).toHaveValue('下载模板草稿')
  await drawer.getByRole('tab',{name:'操作按钮',exact:true}).click()
  const action=drawer.getByRole('textbox',{name:'查看按钮名称',exact:true})
  await action.fill('查看草稿')
  await drawer.getByRole('button',{name:'收起查看草稿',exact:true}).click()
  await expect(action).toBeHidden()
  await drawer.getByRole('button',{name:'收起按钮及顺序',exact:true}).click()
  await drawer.getByRole('button',{name:'展开按钮及顺序',exact:true}).click()
  await expect(action).toBeHidden()
  await drawer.getByRole('button',{name:'展开查看草稿',exact:true}).click()
  await expect(action).toHaveValue('查看草稿')
  await drawer.getByRole('tab',{name:'表格外观',exact:true}).click()
  await drawer.getByRole('button',{name:'收起布局',exact:true}).click()
  await expect(drawer.getByRole('combobox',{name:'表格行高',exact:true})).toBeHidden()
})

for(const scenario of [
  {tab:'列设置',source:'拖动排序 负责人',target:'拖动排序 项目名称 / 客户',row:'.bt-settings-pick'},
  {tab:'操作按钮',source:'拖动操作 删除',target:'拖动操作 查看',row:'.bt-action-setting'},
  {tab:'工具栏',source:'拖动工具 新增报价',target:'拖动工具 模板下载',row:'.bt-tool-config__row'},
])test(`${scenario.tab} reorders at the indicated edge and clears canceled drags`,async({page})=>{
  const drawer=await openSettings(page)
  await drawer.getByRole('tab',{name:scenario.tab,exact:true}).click()
  const source=drawer.getByRole('button',{name:scenario.source,exact:true})
  const target=drawer.locator(scenario.row).filter({has:page.getByRole('button',{name:scenario.target,exact:true})})
  const data=await page.evaluateHandle(()=>new DataTransfer())
  await source.dispatchEvent('dragstart',{dataTransfer:data})
  const box=(await target.boundingBox())!
  await target.dispatchEvent('dragover',{dataTransfer:data,clientY:box.y+2})
  await expect(target).toHaveAttribute('data-reorder-edge','before')
  await source.dispatchEvent('dragend',{dataTransfer:data})
  await expect(drawer.locator('[data-reorder-edge]')).toHaveCount(0)
  await source.dispatchEvent('dragstart',{dataTransfer:data})
  await target.dispatchEvent('drop',{dataTransfer:data,clientY:box.y+2})
  const handles=await drawer.locator(scenario.row+' button[draggable]').evaluateAll(elements=>elements.map(el=>el.getAttribute('aria-label')))
  expect(handles.indexOf(scenario.source)).toBe(handles.indexOf(scenario.target)-1)
  await expect(drawer.locator('[data-reorder-edge]')).toHaveCount(0)
})

test.describe('touch controls',()=>{
  test.use({hasTouch:true,viewport:{width:390,height:900}})
  test('supports explicit move controls and nested font dialog without page overflow',async({page},info)=>{
    await page.goto('/');await page.getByRole('button',{name:'列设置',exact:true}).click()
    const panel=page.getByTestId('column-panel')
    const down=panel.getByRole('button',{name:'下移 项目名称 / 客户',exact:true})
    await expect(down).toBeVisible();await expect(down).toBeInViewport()
    await down.click()
    await expect(panel.getByRole('button',{name:'上移 项目名称 / 客户',exact:true})).toBeEnabled()
    await panel.getByRole('button',{name:'更多设置',exact:true}).click()
    const drawer=page.getByTestId('settings-drawer')
    await drawer.getByRole('button',{name:'编辑列 项目名称 / 客户',exact:true}).click()
    await drawer.getByRole('button',{name:'查找表头文字字体',exact:true}).click()
    const modal=page.getByRole('dialog',{name:'选择字体',exact:true})
    await expect(modal).toBeInViewport()
    expect(await page.evaluate(()=>document.documentElement.scrollWidth)).toBeLessThanOrEqual(390)
    await info.attach('touch-font-dialog',{body:await page.screenshot(),contentType:'image/png'})
    await modal.getByRole('button',{name:'取消',exact:true}).click()
    await expect(drawer).toBeVisible()
  })
})

test('color palette stays inside the scroll area above the preview boundary',async({page},info)=>{
  await page.setViewportSize({width:1920,height:945})
  const drawer=await openSettings(page)
  const color=drawer.locator('[data-color-picker="表头文字"]')
  await color.locator('summary').click()
  const grid=color.locator('.bt-color-presets__grid')
  await expect.poll(async()=>{
    const box=await grid.boundingBox(),area=await drawer.locator('.bt-settings-detail').boundingBox()
    return !!box&&!!area&&box.y>=area.y&&box.y+box.height<=area.y+area.height
  },{message:'all eight swatches must be visible without scrolling or being clipped by the preview'}).toBe(true)
  const white=color.getByRole('button',{name:'使用白色',exact:true})
  expect(await white.evaluate(element=>{
    const box=element.getBoundingClientRect()
    return element.contains(document.elementFromPoint(box.x+box.width/2,box.y+box.height/2))
  })).toBe(true)
  await info.attach('visible-color-palette',{body:await page.screenshot(),contentType:'image/png'})
  await white.click()
  await expect(color.getByRole('textbox',{name:'表头文字文字颜色',exact:true})).toHaveValue('#ffffff')
})

test('number settings use the same display and export interpretation in trial, preview and the saved table',async({page})=>{
  const drawer=await openSettings(page)
  await drawer.getByRole('button',{name:'编辑列 含税金额（元）',exact:true}).click()
  await drawer.getByRole('navigation',{name:'列设置内容'}).getByRole('button',{name:'数字',exact:true}).click()
  await drawer.getByRole('checkbox',{name:'启用数字格式',exact:true}).check()
  await drawer.getByRole('button',{name:'万元两位',exact:true}).click()
  await expect(drawer.getByTestId('settings-preview')).toContainText('6.39万元')
  await expect(page.locator('[data-business-table]')).not.toContainText('6.39万元')
  await drawer.getByRole('button',{name:'应用',exact:true}).click()
  await expect(page.locator('[data-business-table]')).toContainText('6.39万元')
  await page.reload()
  await expect(page.locator('[data-business-table]')).toContainText('6.39万元')
})

test('mapping edits reach real cells and tool previews do not run business actions',async({page})=>{
  const drawer=await openSettings(page)
  await drawer.getByRole('tab',{name:'工具栏',exact:true}).click()
  const preview=drawer.getByTestId('settings-preview')
  await preview.getByRole('button',{name:'新增报价',exact:true}).click()
  await expect(preview.getByRole('status')).toContainText('没有执行操作')
  await expect(page.getByRole('dialog',{name:'新增报价',exact:true})).toHaveCount(0)
  await drawer.getByRole('tab',{name:'列设置',exact:true}).click()
  await drawer.getByRole('button',{name:'编辑列 状态',exact:true}).click()
  await drawer.getByRole('navigation',{name:'列设置内容'}).getByRole('button',{name:'映射',exact:true}).click()
  await drawer.getByRole('checkbox',{name:'启用值映射',exact:true}).check()
  await drawer.getByRole('textbox',{name:'映射文案 1',exact:true}).fill('草稿预览验证')
  await expect(preview).toContainText('草稿预览验证')
  await drawer.getByRole('button',{name:'应用',exact:true}).click()
  await expect(page.locator('[data-business-table]')).toContainText('草稿预览验证')
})
