import {test,expect} from './runtime'

async function openSettings(page:import('@playwright/test').Page){
  await page.goto('/')
  await page.getByTestId('table-settings').click()
  return page.getByTestId('settings-drawer')
}

test('font search and palette change the same draft and apply to the live header',async({page},info)=>{
  await page.setViewportSize({width:1920,height:945})
  const drawer=await openSettings(page)
  await expect(drawer.getByRole('button',{name:'查找表头文字字体',exact:true})).toBeVisible()
  await drawer.getByRole('button',{name:'查找表头文字字体',exact:true}).click()
  const fontDialog=page.getByRole('dialog',{name:'选择字体',exact:true})
  await expect(fontDialog).toBeVisible()
  expect((await fontDialog.boundingBox())!.width).toBe(480)
  // The legacy font dialog must not inherit the surrounding form's padding.
  await expect(fontDialog.getByRole('searchbox')).toHaveCSS('padding-top','0px')
  await expect(fontDialog.getByRole('searchbox')).toHaveCSS('color','rgb(38, 50, 72)')
  await expect(fontDialog.getByRole('button',{name:'关闭字体选择',exact:true})).toHaveCSS('height','32px')
  await expect(fontDialog).toHaveCSS('font-synthesis','none')
  await expect(fontDialog.getByRole('searchbox',{name:'搜索字体'})).toBeFocused()
  await fontDialog.getByRole('searchbox').fill('雅黑')
  await expect(fontDialog.getByRole('option')).toHaveCount(1)
  await info.attach('font-search',{body:await page.screenshot(),contentType:'image/png'})
  await page.keyboard.press('ArrowDown')
  await page.keyboard.press('Enter')
  await expect(fontDialog).toHaveCount(0)
  await expect(drawer.getByRole('combobox',{name:'表头文字字体',exact:true})).toBeFocused()
  const color=drawer.locator('[data-color-picker="表头文字"]')
  await expect(color.getByRole('textbox',{name:'表头文字文字颜色',exact:true})).toHaveValue('')
  await color.locator('summary').click()
  await color.getByRole('button',{name:'使用深蓝色',exact:true}).click()
  const header=page.locator('.vxe-table--main-wrapper .vxe-header--column').filter({hasText:'项目名称 / 客户'}).locator('.bt__sort')
  const previous=await header.evaluate(el=>getComputedStyle(el).color)
  expect(previous).not.toBe('rgb(36, 104, 232)')
  await drawer.getByRole('button',{name:'应用',exact:true}).click()
  await expect(header).toHaveCSS('color','rgb(36, 104, 232)')
  await expect(header).toHaveCSS('font-family',/Microsoft YaHei/)
})

test('invalid color remains editable across columns and cannot be silently applied',async({page})=>{
  const drawer=await openSettings(page)
  await drawer.getByRole('textbox',{name:'显示名称',exact:true}).fill('待确认名称')
  const input=drawer.getByRole('textbox',{name:'表头文字文字颜色',exact:true})
  await input.fill('#oops')
  await expect(input).toHaveAttribute('aria-invalid','true')
  await expect(drawer.getByRole('button',{name:'应用',exact:true})).toBeDisabled()
  await drawer.getByRole('button',{name:'编辑列 负责人',exact:true}).click()
  await expect(drawer.getByRole('button',{name:'应用',exact:true})).toBeDisabled()
  await drawer.getByRole('button',{name:'定位颜色错误',exact:true}).click()
  await expect(input).toHaveValue('#oops')
  await expect(input).toBeFocused()
  await input.fill('#167457')
  await expect(drawer.getByRole('button',{name:'应用',exact:true})).toBeEnabled()
  await drawer.getByRole('button',{name:'取消',exact:true}).click()
  await expect(page.locator('.vxe-table--main-wrapper .vxe-header--column').filter({hasText:'待确认名称'})).toHaveCount(0)
})

test('nested Escape and alignment keys retain the editor instead of dismissing it',async({page})=>{
  const drawer=await openSettings(page)
  const trigger=drawer.getByRole('button',{name:'查找表头文字字体',exact:true})
  await expect(trigger).toBeVisible()
  await trigger.click()
  await page.getByRole('searchbox',{name:'搜索字体'}).fill('找不到')
  await expect(page.getByText('没有匹配的字体',{exact:true})).toBeVisible()
  await page.keyboard.press('Escape')
  await expect(drawer).toBeVisible()
  await expect(page.getByRole('dialog',{name:'选择字体',exact:true})).toHaveCount(0)
  const palette=drawer.locator('[data-color-picker="表头文字"] summary')
  await palette.click()
  await page.keyboard.press('Escape')
  await expect(palette).toBeFocused()
  await expect(drawer).toBeVisible()
  const initial=drawer.getByRole('button',{name:'表头文字默认对齐',exact:true})
  await initial.focus();await page.keyboard.press('ArrowRight')
  const left=drawer.getByRole('button',{name:'表头文字左对齐',exact:true})
  await expect(left).toBeFocused();await expect(left).toHaveAttribute('aria-pressed','true')
  await page.keyboard.press('End')
  await expect(drawer.getByRole('button',{name:'表头文字右对齐',exact:true})).toBeFocused()
})

test('quick hidden columns have the legacy strike-through and hidden pins do not catch clicks',async({page})=>{
  await page.goto('/');await page.getByTestId('column-settings').click()
  const panel=page.getByTestId('column-panel')
  const hidden=panel.locator('.bt-column-popup__row').filter({has:page.getByRole('checkbox',{name:'显示客户',exact:true})})
  await expect(hidden.locator('.bt-column-popup__name')).toHaveCSS('text-decoration-line','line-through')
  const ordinary=panel.locator('.bt-column-popup__row').filter({has:page.getByRole('checkbox',{name:'显示负责人',exact:true})})
  await page.mouse.move(0,0)
  await expect(ordinary.locator('.bt-column-popup__pins')).toHaveCSS('pointer-events','none')
  await ordinary.hover()
  await expect(ordinary.locator('.bt-column-popup__pins')).toHaveCSS('pointer-events','auto')
})

test('column context stays visible while scrolling settings content',async({page},info)=>{
  await page.setViewportSize({width:1920,height:945})
  const drawer=await openSettings(page)
  const detail=drawer.locator('.bt-settings-detail')
  await detail.evaluate(el=>{el.scrollTop=el.scrollHeight})
  const context=drawer.locator('.bt-settings-detail__heading')
  const panelBox=await detail.boundingBox(),headingBox=await context.boundingBox()
  expect(headingBox!.y).toBeGreaterThanOrEqual(panelBox!.y-1)
  await expect(context).toBeInViewport()
  await info.attach('scrolled-settings',{body:await page.screenshot(),contentType:'image/png'})
})

test.describe('touch controls',()=>{
  test.use({hasTouch:true,viewport:{width:390,height:900}})
  test('supports explicit move controls and nested font dialog without page overflow',async({page},info)=>{
    await page.goto('/');await page.getByTestId('column-settings').click()
    const panel=page.getByTestId('column-panel')
    const down=panel.getByRole('button',{name:'下移 项目名称 / 客户',exact:true})
    await expect(down).toBeVisible();await expect(down).toBeInViewport()
    await down.click()
    await expect(panel.getByRole('button',{name:'上移 项目名称 / 客户',exact:true})).toBeEnabled()
    await panel.getByRole('button',{name:'更多设置',exact:true}).click()
    const drawer=page.getByTestId('settings-drawer')
    await drawer.getByRole('button',{name:'编辑列 项目名称 / 客户',exact:true}).click()
    await drawer.getByRole('button',{name:'查找表头文字字体',exact:true}).click()
    const modal=page.getByRole('dialog',{name:'选择字体',exact:true})
    await expect(modal).toBeInViewport()
    expect(await page.evaluate(()=>document.documentElement.scrollWidth)).toBeLessThanOrEqual(390)
    await info.attach('touch-font-dialog',{body:await page.screenshot(),contentType:'image/png'})
    await modal.getByRole('button',{name:'取消',exact:true}).click()
    await expect(drawer).toBeVisible()
  })
})

test('color palette stays inside the scroll area above the preview boundary',async({page},info)=>{
  await page.setViewportSize({width:1920,height:945})
  const drawer=await openSettings(page)
  const color=drawer.locator('[data-color-picker="表头文字"]')
  await color.locator('summary').click()
  const grid=color.locator('.bt-color-presets__grid')
  await expect.poll(async()=>{
    const box=await grid.boundingBox(),area=await drawer.locator('.bt-settings-detail').boundingBox()
    return !!box&&!!area&&box.y>=area.y&&box.y+box.height<=area.y+area.height
  },{message:'all eight swatches must be visible without scrolling or being clipped by the preview'}).toBe(true)
  const white=color.getByRole('button',{name:'使用白色',exact:true})
  expect(await white.evaluate(element=>{
    const box=element.getBoundingClientRect()
    return element.contains(document.elementFromPoint(box.x+box.width/2,box.y+box.height/2))
  })).toBe(true)
  await info.attach('visible-color-palette',{body:await page.screenshot(),contentType:'image/png'})
  await white.click()
  await expect(color.getByRole('textbox',{name:'表头文字文字颜色',exact:true})).toHaveValue('#ffffff')
})
