import {test as networkTest} from '@playwright/test'
import {test,expect} from './runtime'

async function openSettings(page:import('@playwright/test').Page){
  await page.goto('/')
  await page.getByRole('button',{name:'表格设置',exact:true}).click()
  return page.getByTestId('settings-drawer')
}

test('range controls share exact drafts, reject invalid numbers and apply only on confirmation',async({page})=>{
  await page.setViewportSize({width:1440,height:900})
  const drawer=await openSettings(page)
  await drawer.getByRole('tab',{name:'表格外观',exact:true}).click()
  const size=drawer.getByRole('spinbutton',{name:'内容字号',exact:true})
  const slider=drawer.getByRole('slider',{name:'内容字号滑动条',exact:true})
  await slider.focus();await page.keyboard.press('End')
  await expect(size).toHaveValue('32')
  await expect(drawer.locator('.bt-settings-preview__table')).toHaveCSS('font-size','32px')
  const track=(await slider.boundingBox())!
  await page.mouse.click(track.x+track.width/2,track.y+track.height/2)
  await expect(size).toHaveValue('21')
  await size.fill('99')
  await expect(size).toHaveAttribute('aria-invalid','true')
  await expect(drawer.getByRole('button',{name:'应用',exact:true})).toBeDisabled()
  await drawer.getByRole('tab',{name:'工具栏',exact:true}).click()
  await expect(drawer.getByRole('button',{name:'应用',exact:true})).toBeDisabled()
  await drawer.getByRole('tab',{name:'表格外观',exact:true}).click()
  await expect(size).toHaveValue('99')
  await drawer.getByRole('button',{name:'恢复当前页',exact:true}).click()
  await expect(size).toHaveValue('14')
  await expect(size).toHaveAttribute('aria-invalid','false')
  await size.fill('17')
  await expect(slider).toHaveValue('17')
  await drawer.getByRole('button',{name:'收起默认文字',exact:true}).click()
  await drawer.getByRole('button',{name:'展开默认文字',exact:true}).click()
  await expect(size).toHaveValue('17')
  await drawer.getByRole('button',{name:'取消',exact:true}).click()
  await page.getByRole('button',{name:'表格设置',exact:true}).click()
  await drawer.getByRole('tab',{name:'表格外观',exact:true}).click()
  await expect(size).toHaveValue('14')
  await size.fill('18')
  await drawer.getByRole('button',{name:'应用',exact:true}).click()
  await page.getByRole('button',{name:'表格设置',exact:true}).click()
  await drawer.getByRole('tab',{name:'表格外观',exact:true}).click()
  await expect(size).toHaveValue('18')
})

test('numeric restore clears only its column or style scope, including unchanged defaults',async({page})=>{
  const drawer=await openSettings(page)
  const headerSize=drawer.getByRole('spinbutton',{name:'表头文字字号',exact:true})
  const cellSize=drawer.getByRole('spinbutton',{name:'单元格文字字号',exact:true})
  await headerSize.fill('99');await cellSize.fill('99')
  const headerSection=drawer.locator('.bt-settings-section').filter({has:page.getByRole('heading',{name:'表头文字',exact:true})})
  await headerSection.getByRole('button',{name:'恢复',exact:true}).click()
  await expect(headerSize).toHaveValue('14')
  await expect(cellSize).toHaveValue('99')
  await drawer.getByRole('button',{name:'编辑列 负责人',exact:true}).click()
  await headerSize.fill('99')
  await drawer.getByRole('button',{name:'恢复此列',exact:true}).click()
  await expect(headerSize).toHaveValue('14')
  await expect(drawer.getByRole('button',{name:'应用',exact:true})).toBeDisabled()
  await drawer.getByRole('button',{name:'编辑列 项目名称 / 客户',exact:true}).click()
  await expect(cellSize).toHaveValue('99')
  await drawer.getByRole('button',{name:'恢复此列',exact:true}).click()
  await expect(cellSize).toHaveValue('14')
  await expect(cellSize).toHaveAttribute('aria-invalid','false')
})

test('invalid numeric drafts participate in close confirmation and page restoration',async({page})=>{
  const drawer=await openSettings(page)
  await drawer.getByRole('spinbutton',{name:'单元格文字字号',exact:true}).fill('99')
  await drawer.getByRole('button',{name:'关闭表格设置',exact:true}).click()
  await expect(page.getByRole('alertdialog',{name:'放弃未应用的修改'})).toBeVisible()
  await page.getByRole('button',{name:'继续编辑',exact:true}).click()
  await drawer.getByRole('button',{name:'恢复此列',exact:true}).click()
  await drawer.getByRole('tab',{name:'表格外观',exact:true}).click()
  await expect(drawer.getByRole('heading',{name:'设置备份',exact:true})).toHaveCount(0)
  await expect(drawer.getByLabel('恢复表格设置文件')).toHaveCount(0)
  await drawer.getByRole('spinbutton',{name:'内容字号',exact:true}).fill('18')
  await expect(drawer.getByRole('button',{name:'应用',exact:true})).toBeEnabled()
  await drawer.getByRole('tab',{name:'列设置',exact:true}).click()
  await expect(drawer.getByRole('spinbutton',{name:'单元格文字字号',exact:true})).toHaveValue('18')
  await expect(drawer.getByRole('spinbutton',{name:'单元格文字字号',exact:true})).toHaveAttribute('aria-invalid','false')
})

test('compact settings keep tools and action controls inside desktop and mobile panels',async({page},info)=>{
  await page.setViewportSize({width:1440,height:900})
  const drawer=await openSettings(page)
  // Composited enter transforms can introduce subpixel rounding in the rect.
  expect((await drawer.boundingBox())!.width).toBeCloseTo(920,2)
  await drawer.getByRole('tab',{name:'工具栏',exact:true}).click()
  const rows=drawer.locator('.bt-tool-config__row')
  expect((await rows.first().boundingBox())!.height).toBeLessThanOrEqual(44)
  await drawer.getByRole('slider',{name:'工具间距滑动条',exact:true}).focus()
  await page.keyboard.press('Home');await page.keyboard.press('ArrowRight')
  await expect(drawer.getByRole('spinbutton',{name:'工具间距',exact:true})).toHaveValue('1')
  await page.setViewportSize({width:390,height:844})
  for(const tab of ['工具栏','操作按钮','表格外观','排序规则']){
    await drawer.getByRole('tab',{name:tab,exact:true}).click()
    expect(await drawer.evaluate(el=>el.scrollWidth<=el.clientWidth)).toBe(true)
    const pane=drawer.locator('.bt-settings-page,.bt-settings-sort-page')
    expect(await pane.evaluate(el=>el.scrollWidth<=el.clientWidth)).toBe(true)
    const screenshotNames:Record<string,string>={'工具栏':'toolbar','操作按钮':'actions','表格外观':'appearance','排序规则':'sorts'}
    await page.screenshot({path:info.outputPath(screenshotNames[tab]+'-narrow.png')})
  }
})

test('font search and palette change the same draft and apply to the live header',async({page},info)=>{
  await page.setViewportSize({width:1920,height:945})
  const drawer=await openSettings(page)
  await expect(drawer.getByRole('button',{name:'查找表头文字字体',exact:true})).toBeVisible()
  await drawer.getByRole('button',{name:'查找表头文字字体',exact:true}).click()
  const fontDialog=page.getByRole('dialog',{name:'选择字体',exact:true})
  await expect(fontDialog).toBeVisible()
  expect((await fontDialog.boundingBox())!.width).toBe(480)
  // The legacy font dialog must not inherit the surrounding form's padding.
  await expect(fontDialog.getByRole('searchbox')).toHaveCSS('padding-top','0px')
  await expect(fontDialog.getByRole('searchbox')).toHaveCSS('color','rgb(38, 50, 72)')
  await expect(fontDialog.getByRole('button',{name:'关闭字体选择',exact:true})).toHaveCSS('height','32px')
  await expect(fontDialog).toHaveCSS('font-synthesis','none')
  await expect(fontDialog.getByRole('searchbox',{name:'搜索字体'})).toBeFocused()
  await fontDialog.getByRole('searchbox').fill('雅黑')
  await expect(fontDialog.getByRole('option')).toHaveCount(1)
  await info.attach('font-search',{body:await page.screenshot(),contentType:'image/png'})
  await page.keyboard.press('ArrowDown')
  await page.keyboard.press('Enter')
  await expect(fontDialog).toHaveCount(0)
  await expect(drawer.getByRole('combobox',{name:'表头文字字体',exact:true})).toBeFocused()
  const color=drawer.locator('[data-color-picker="表头文字"]')
  await expect(color.getByRole('textbox',{name:'表头文字文字颜色',exact:true})).toHaveValue('')
  await color.locator('summary').click()
  await color.getByRole('button',{name:'使用深蓝色',exact:true}).click()
  const header=page.locator('.vxe-table--main-wrapper .vxe-header--column').filter({hasText:'项目名称 / 客户'}).locator('.bt__sort')
  const previous=await header.evaluate(el=>getComputedStyle(el).color)
  expect(previous).not.toBe('rgb(36, 104, 232)')
  await drawer.getByRole('button',{name:'应用',exact:true}).click()
  await expect(header).toHaveCSS('color','rgb(36, 104, 232)')
  await expect(header).toHaveCSS('font-family',/Microsoft YaHei/)
})

test('invalid color remains editable across columns and cannot be silently applied',async({page})=>{
  const drawer=await openSettings(page)
  await drawer.getByRole('textbox',{name:'显示名称',exact:true}).fill('待确认名称')
  const input=drawer.getByRole('textbox',{name:'表头文字文字颜色',exact:true})
  await input.fill('#oops')
  await expect(input).toHaveAttribute('aria-invalid','true')
  await expect(drawer.getByRole('button',{name:'应用',exact:true})).toBeDisabled()
  await drawer.getByRole('button',{name:'编辑列 负责人',exact:true}).click()
  await expect(drawer.getByRole('button',{name:'应用',exact:true})).toBeDisabled()
  await drawer.getByRole('button',{name:'定位颜色错误',exact:true}).click()
  await expect(input).toHaveValue('#oops')
  await expect(input).toBeFocused()
  await input.fill('#167457')
  await expect(drawer.getByRole('button',{name:'应用',exact:true})).toBeEnabled()
  await drawer.getByRole('button',{name:'取消',exact:true}).click()
  await expect(page.locator('.vxe-table--main-wrapper .vxe-header--column').filter({hasText:'待确认名称'})).toHaveCount(0)
})

test('nested Escape and alignment keys retain the editor instead of dismissing it',async({page})=>{
  const drawer=await openSettings(page)
  const trigger=drawer.getByRole('button',{name:'查找表头文字字体',exact:true})
  await expect(trigger).toBeVisible()
  await trigger.click()
  await page.getByRole('searchbox',{name:'搜索字体'}).fill('找不到')
  await expect(page.getByText('没有匹配的字体',{exact:true})).toBeVisible()
  await page.keyboard.press('Escape')
  await expect(drawer).toBeVisible()
  await expect(page.getByRole('dialog',{name:'选择字体',exact:true})).toHaveCount(0)
  const palette=drawer.locator('[data-color-picker="表头文字"] summary')
  await palette.click()
  await page.keyboard.press('Escape')
  await expect(palette).toBeFocused()
  await expect(drawer).toBeVisible()
  const initial=drawer.getByRole('button',{name:'表头文字默认对齐',exact:true})
  await initial.focus();await page.keyboard.press('ArrowRight')
  const left=drawer.getByRole('button',{name:'表头文字左对齐',exact:true})
  await expect(left).toBeFocused();await expect(left).toHaveAttribute('aria-pressed','true')
  await page.keyboard.press('End')
  await expect(drawer.getByRole('button',{name:'表头文字右对齐',exact:true})).toBeFocused()
})

test('quick hidden columns have the legacy strike-through and hidden pins do not catch clicks',async({page})=>{
  await page.goto('/');await page.getByRole('button',{name:'列设置',exact:true}).click()
  const panel=page.getByTestId('column-panel')
  const hidden=panel.locator('.bt-column-popup__row').filter({has:page.getByRole('checkbox',{name:'显示客户',exact:true})})
  await expect(hidden.locator('.bt-column-popup__name')).toHaveCSS('text-decoration-line','line-through')
  const ordinary=panel.locator('.bt-column-popup__row').filter({has:page.getByRole('checkbox',{name:'显示负责人',exact:true})})
  await page.mouse.move(0,0)
  await expect(ordinary.locator('.bt-column-popup__pins')).toHaveCSS('pointer-events','none')
  await ordinary.hover()
  await expect(ordinary.locator('.bt-column-popup__pins')).toHaveCSS('pointer-events','auto')
})

test('column context stays visible while scrolling settings content',async({page},info)=>{
  await page.setViewportSize({width:1920,height:945})
  const drawer=await openSettings(page)
  const detail=drawer.locator('.bt-settings-detail')
  const header=drawer.locator('.bt-settings-editor-header')
  const before=await header.boundingBox()
  await detail.evaluate(el=>{el.scrollTop=el.scrollHeight})
  await expect.poll(async()=>Math.abs((await header.boundingBox())!.y-before!.y)).toBeLessThanOrEqual(1)
  const context=drawer.locator('.bt-settings-detail__heading')
  const panelBox=await drawer.locator('.bt-settings-editor').boundingBox(),headingBox=await context.boundingBox()
  expect(headingBox!.y).toBeGreaterThanOrEqual(panelBox!.y-1)
  await expect(context).toBeInViewport()
  await info.attach('scrolled-settings',{body:await page.screenshot(),contentType:'image/png'})
})

test('all column sections collapse without losing drafts and navigation expands its destination',async({page})=>{
  const drawer=await openSettings(page)
  const name=drawer.getByRole('textbox',{name:'显示名称',exact:true})
  await name.fill('未应用的列名称')
  await drawer.getByRole('button',{name:'收起基本',exact:true}).click()
  await expect(name).toBeHidden()
  await drawer.getByRole('navigation',{name:'列设置内容'}).getByRole('button',{name:'基本',exact:true}).click()
  await expect(name).toBeVisible()
  await expect(name).toHaveValue('未应用的列名称')
  for(const title of ['表头文字','单元格文字','内容显示','列筛选','值映射','富文本显示模板','规则试算']){
    await drawer.getByRole('button',{name:'收起'+title,exact:true}).click()
    await expect(drawer.getByRole('button',{name:'展开'+title,exact:true})).toHaveAttribute('aria-expanded','false')
  }
  await drawer.getByRole('navigation',{name:'列设置内容'}).getByRole('button',{name:'筛选',exact:true}).click()
  await expect(drawer.getByRole('checkbox',{name:'允许列筛选',exact:true})).toBeInViewport()
  await expect(drawer.getByRole('button',{name:'收起列筛选',exact:true})).toHaveAttribute('aria-expanded','true')
  await drawer.getByRole('button',{name:'取消',exact:true}).click()
  await expect(page.locator('[data-business-table]')).not.toContainText('未应用的列名称')
})

test('quick column drag indicates the insertion edge and does not apply the draft until confirmed',async({page})=>{
  await page.goto('/');await page.getByRole('button',{name:'列设置',exact:true}).click()
  const panel=page.getByTestId('column-panel'),rows=panel.locator('.bt-column-popup__row')
  const source=panel.getByRole('button',{name:'拖动排序 状态',exact:true})
  const target=rows.filter({has:page.getByRole('checkbox',{name:'显示项目名称 / 客户',exact:true})})
  const handle=(await source.boundingBox())!
  await page.mouse.move(handle.x+handle.width/2,handle.y+handle.height/2)
  await page.mouse.down()
  await page.mouse.move(handle.x+handle.width/2+6,handle.y+handle.height/2,{steps:3})
  const box=(await target.boundingBox())!
  await page.mouse.move(box.x+box.width/2,box.y+2,{steps:5})
  await page.mouse.move(box.x+box.width/2+1,box.y+2)
  await expect(target).toHaveAttribute('data-reorder-edge','before')
  await expect(target).toHaveCSS('position','relative')
  expect(await target.evaluate(el=>getComputedStyle(el,'::after').height)).toBe('2px')
  await page.mouse.up()
  await expect(panel.locator('[data-reorder-edge]')).toHaveCount(0)
  const names=await rows.locator('.bt-column-popup__name').allTextContents()
  expect(names.slice(0,3)).toEqual(['报价编号','状态','项目名称 / 客户'])
  await panel.getByRole('button',{name:'取消',exact:true}).click()
  const headers=page.locator('.vxe-table--main-wrapper .vxe-header--column')
  expect((await headers.allTextContents()).join('')).toMatch(/项目名称.*状态/)
})

test('toolbar and action settings collapse by level while preserving edited values',async({page})=>{
  const drawer=await openSettings(page)
  await drawer.getByRole('tab',{name:'工具栏',exact:true}).click()
  const tool=drawer.getByRole('textbox',{name:'模板下载工具名称',exact:true})
  await tool.fill('下载模板草稿')
  await drawer.getByRole('button',{name:'收起页面工具栏',exact:true}).click()
  await expect(tool).toBeHidden()
  await expect(drawer.getByRole('textbox',{name:'刷新工具名称',exact:true})).toBeVisible()
  await drawer.getByRole('button',{name:'展开页面工具栏',exact:true}).click()
  await expect(tool).toHaveValue('下载模板草稿')
  await drawer.getByRole('tab',{name:'操作按钮',exact:true}).click()
  const action=drawer.getByRole('textbox',{name:'查看按钮名称',exact:true})
  await action.fill('查看草稿')
  await drawer.getByRole('button',{name:'收起二级菜单',exact:true}).click()
  await drawer.getByRole('button',{name:'收起按钮及顺序',exact:true}).click()
  await expect(action).toBeHidden()
  await drawer.getByRole('button',{name:'展开按钮及顺序',exact:true}).click()
  await expect(drawer.getByRole('button',{name:'展开二级菜单',exact:true})).toBeVisible()
  await expect(action).toHaveValue('查看草稿')
  await drawer.getByRole('tab',{name:'表格外观',exact:true}).click()
  await drawer.getByRole('button',{name:'收起布局',exact:true}).click()
  await expect(drawer.getByRole('combobox',{name:'表格行高',exact:true})).toBeHidden()
})

for(const scenario of [
  {tab:'列设置',source:'拖动排序 状态',target:'拖动排序 项目名称 / 客户',row:'.bt-settings-pick'},
  {tab:'操作按钮',source:'拖动操作 删除',target:'拖动操作 查看',row:'.bt-action-setting'},
  {tab:'工具栏',source:'拖动工具 新增报价',target:'拖动工具 模板下载',row:'.bt-tool-config__row'},
])test(`${scenario.tab} reorders at the indicated edge and clears canceled drags`,async({page})=>{
  await page.setViewportSize({width:1440,height:1000})
  const drawer=await openSettings(page)
  await drawer.getByRole('tab',{name:scenario.tab,exact:true}).click()
  const source=drawer.getByRole('button',{name:scenario.source,exact:true})
  await expect(source).toBeVisible()
  if(scenario.tab==='操作按钮'){
    const headings=drawer.locator('.bt-action-setting > header button[aria-expanded="true"]')
    while(await headings.count())await headings.first().click()
  }
  const target=drawer.locator(scenario.row).filter({has:page.getByRole('button',{name:scenario.target,exact:true})})
  const before=await drawer.locator(scenario.row+' [data-reorder-handle]').evaluateAll(elements=>elements.map(el=>el.getAttribute('aria-label')))
  async function begin(){
    await source.scrollIntoViewIfNeeded()
    const handle=(await source.boundingBox())!,box=(await target.boundingBox())!
    await page.mouse.move(handle.x+handle.width/2,handle.y+handle.height/2)
    await page.mouse.down();await page.mouse.move(handle.x+handle.width/2+8,handle.y+handle.height/2,{steps:3})
    await page.mouse.move(box.x+box.width/2,box.y+2,{steps:6})
    await page.mouse.move(box.x+box.width/2+1,box.y+2)
  }
  await begin()
  await expect(target).toHaveAttribute('data-reorder-edge','before')
  await page.keyboard.press('Escape');await page.mouse.up()
  await expect(drawer.locator('[data-reorder-edge]')).toHaveCount(0)
  expect(await drawer.locator(scenario.row+' [data-reorder-handle]').evaluateAll(elements=>elements.map(el=>el.getAttribute('aria-label')))).toEqual(before)
  await begin();await expect(target).toHaveAttribute('data-reorder-edge','before');await page.mouse.up()
  const handles=await drawer.locator(scenario.row+' [data-reorder-handle]').evaluateAll(elements=>elements.map(el=>el.getAttribute('aria-label')))
  expect(handles.indexOf(scenario.source)).toBe(handles.indexOf(scenario.target)-1)
  await expect(drawer.locator('[data-reorder-edge]')).toHaveCount(0)
  await expect(page.locator('.bt-reorder-fallback,.bt-reorder-ghost,.bt-reorder-chosen')).toHaveCount(0)
})

test('dragging near the scroll edge scrolls the list and Escape leaves order unchanged',async({page})=>{
  await page.goto('/');await page.getByRole('button',{name:'列设置',exact:true}).click()
  const panel=page.getByTestId('column-panel'),list=panel.locator('.bt-column-popup__list')
  await expect(panel.getByRole('button',{name:'拖动排序 状态',exact:true})).toBeVisible()
  const original=await panel.locator('.bt-column-popup__name').allTextContents()
  const handle=(await panel.getByRole('button',{name:'拖动排序 状态',exact:true}).boundingBox())!,box=(await list.boundingBox())!
  await page.mouse.move(handle.x+handle.width/2,handle.y+handle.height/2);await page.mouse.down()
  await page.mouse.move(handle.x+handle.width/2+8,handle.y+handle.height/2,{steps:3})
  await page.mouse.move(box.x+box.width/2,box.y+box.height-5,{steps:6})
  await page.mouse.move(box.x+box.width/2+1,box.y+box.height-5)
  await expect.poll(()=>list.evaluate(element=>element.scrollTop)).toBeGreaterThan(0)
  await page.keyboard.press('Escape');await page.mouse.up()
  await expect(page.locator('.bt-reorder-fallback,.bt-reorder-ghost,.bt-reorder-chosen,[data-reorder-edge]')).toHaveCount(0)
  expect(await panel.locator('.bt-column-popup__name').allTextContents()).toEqual(original)
})

test.describe('touch controls',()=>{
  test.use({hasTouch:true,viewport:{width:390,height:900}})
  test('touch dragging uses insertion edges and removes its fallback ghost after release',async({page})=>{
    await page.goto('/');await page.getByRole('button',{name:'列设置',exact:true}).click()
    const panel=page.getByTestId('column-panel'),rows=panel.locator('.bt-column-popup__row')
    const handle=(await panel.getByRole('button',{name:'拖动排序 状态',exact:true}).boundingBox())!
    const target=rows.filter({has:page.getByRole('checkbox',{name:'显示项目名称 / 客户',exact:true})}),box=(await target.boundingBox())!
    const touch=await page.context().newCDPSession(page)
    await touch.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:handle.x+handle.width/2,y:handle.y+handle.height/2}]})
    // Exercise the intentional long-press threshold before starting a touch drag.
    await page.waitForTimeout(160)
    await touch.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:handle.x+handle.width/2+8,y:handle.y+handle.height/2}]})
    await touch.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:box.x+box.width/2,y:box.y+2}]})
    await expect(target).toHaveAttribute('data-reorder-edge','before')
    await expect(page.locator('.bt-reorder-fallback')).toHaveCount(1)
    await touch.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]})
    await expect(page.locator('.bt-reorder-fallback,.bt-reorder-ghost,.bt-reorder-chosen')).toHaveCount(0)
    expect((await rows.locator('.bt-column-popup__name').allTextContents()).slice(0,3)).toEqual(['报价编号','状态','项目名称 / 客户'])
    await touch.detach()
  })
  test('supports explicit move controls and nested font dialog without page overflow',async({page},info)=>{
    await page.goto('/');await page.getByRole('button',{name:'列设置',exact:true}).click()
    const panel=page.getByTestId('column-panel')
    const down=panel.getByRole('button',{name:'下移 项目名称 / 客户',exact:true})
    await expect(down).toBeVisible();await expect(down).toBeInViewport()
    await down.click()
    await expect(panel.getByRole('button',{name:'上移 项目名称 / 客户',exact:true})).toBeEnabled()
    await panel.getByRole('button',{name:'更多设置',exact:true}).click()
    const drawer=page.getByTestId('settings-drawer')
    await drawer.getByRole('button',{name:'编辑列 项目名称 / 客户',exact:true}).click()
    await drawer.getByRole('button',{name:'查找表头文字字体',exact:true}).click()
    const modal=page.getByRole('dialog',{name:'选择字体',exact:true})
    await expect(modal).toBeInViewport()
    expect(await page.evaluate(()=>document.documentElement.scrollWidth)).toBeLessThanOrEqual(390)
    await info.attach('touch-font-dialog',{body:await page.screenshot(),contentType:'image/png'})
    await modal.getByRole('button',{name:'取消',exact:true}).click()
    await expect(drawer).toBeVisible()
  })
})

test('color palette stays inside the scroll area above the preview boundary',async({page},info)=>{
  await page.setViewportSize({width:1920,height:945})
  const drawer=await openSettings(page)
  const color=drawer.locator('[data-color-picker="表头文字"]')
  await color.locator('summary').click()
  const grid=color.locator('.bt-color-presets__grid')
  await expect.poll(async()=>{
    const box=await grid.boundingBox(),area=await drawer.locator('.bt-settings-detail').boundingBox()
    return !!box&&!!area&&box.y>=area.y&&box.y+box.height<=area.y+area.height
  },{message:'all eight swatches must be visible without scrolling or being clipped by the preview'}).toBe(true)
  const white=color.getByRole('button',{name:'使用白色',exact:true})
  expect(await white.evaluate(element=>{
    const box=element.getBoundingClientRect()
    return element.contains(document.elementFromPoint(box.x+box.width/2,box.y+box.height/2))
  })).toBe(true)
  await info.attach('visible-color-palette',{body:await page.screenshot(),contentType:'image/png'})
  await white.click()
  await expect(color.getByRole('textbox',{name:'表头文字文字颜色',exact:true})).toHaveValue('#ffffff')
})

test('number settings use the same display and export interpretation in trial, preview and the saved table',async({page})=>{
  const drawer=await openSettings(page)
  await drawer.getByRole('button',{name:'编辑列 含税金额（元）',exact:true}).click()
  await drawer.getByRole('navigation',{name:'列设置内容'}).getByRole('button',{name:'数字',exact:true}).click()
  await drawer.getByRole('checkbox',{name:'启用数字格式',exact:true}).check()
  await drawer.getByRole('button',{name:'万元两位',exact:true}).click()
  await expect(drawer.getByTestId('settings-preview')).toContainText('6.39万元')
  await expect(page.locator('[data-business-table]')).not.toContainText('6.39万元')
  await drawer.getByRole('button',{name:'应用',exact:true}).click()
  await expect(page.locator('[data-business-table]')).toContainText('6.39万元')
  await page.reload()
  await expect(page.locator('[data-business-table]')).toContainText('6.39万元')
})

test('mapping edits reach real cells and tool previews do not run business actions',async({page})=>{
  const drawer=await openSettings(page)
  await drawer.getByRole('tab',{name:'工具栏',exact:true}).click()
  const preview=drawer.getByTestId('settings-preview')
  await preview.getByRole('button',{name:'新增报价',exact:true}).click()
  await expect(preview.getByRole('status')).toContainText('没有执行操作')
  await expect(page.getByRole('dialog',{name:'新增报价',exact:true})).toHaveCount(0)
  await drawer.getByRole('tab',{name:'列设置',exact:true}).click()
  await drawer.getByRole('button',{name:'编辑列 状态',exact:true}).click()
  await drawer.getByRole('navigation',{name:'列设置内容'}).getByRole('button',{name:'映射',exact:true}).click()
  await drawer.getByRole('checkbox',{name:'启用值映射',exact:true}).check()
  await drawer.getByRole('textbox',{name:'映射文案 1',exact:true}).fill('草稿预览验证')
  await expect(preview).toContainText('草稿预览验证')
  await drawer.getByRole('button',{name:'应用',exact:true}).click()
  await expect(page.locator('[data-business-table]')).toContainText('草稿预览验证')
})


test('intent loads settings and template code without opening or mounting editors',async({page},info)=>{
  const settingsModule=/\/ColumnSettings(?:\.vue(?:\?|$)|-[^/]+\.js$)/
  const editorModule=/\/RichEditor(?:\.vue(?:\?|$)|-[^/]+\.js$)/
  const requests:string[]=[]
  page.on('request',request=>requests.push(request.url()))
  await page.goto('/')
  const trigger=page.getByRole('button',{name:'表格设置',exact:true})
  await expect(trigger).toBeVisible()
  expect(requests.some(url=>settingsModule.test(url))).toBe(false)
  expect(requests.some(url=>editorModule.test(url))).toBe(false)
  const settingsReady=page.waitForResponse(response=>settingsModule.test(response.url()))
  await trigger.hover();await settingsReady
  await expect(page.getByTestId('settings-drawer')).toHaveCount(0)
  const start=Date.now();await trigger.click()
  const drawer=page.getByTestId('settings-drawer');await expect(drawer).toBeVisible()
  const settingsMs=Date.now()-start
  const edit=drawer.getByRole('button',{name:'编辑模板',exact:true})
  expect(requests.some(url=>editorModule.test(url))).toBe(false)
  let release!:()=>void
  const held=new Promise<void>(resolve=>{release=resolve})
  await page.route(editorModule,async route=>{await held;await route.continue()})
  const requested=page.waitForRequest(editorModule)
  await edit.focus();await requested
  await expect(page.getByRole('dialog',{name:'编辑列显示模板',exact:true})).toHaveCount(0)
  await expect(page.locator('.tiptap')).toHaveCount(0)
  await edit.click()
  const dialog=page.getByRole('dialog',{name:'编辑列显示模板',exact:true})
  await expect(dialog).toBeVisible()
  await expect(dialog.getByRole('status')).toHaveText('正在加载编辑器…')
  await expect(dialog.getByRole('button',{name:'使用模板',exact:true})).toBeDisabled()
  const editorStart=Date.now();release()
  await expect(dialog.getByRole('textbox',{name:'列显示模板',exact:true})).toBeVisible()
  await expect(dialog.getByRole('button',{name:'使用模板',exact:true})).toBeEnabled()
  await expect(dialog.locator('.tiptap')).toHaveCount(1)
  await info.attach('first-open-sample',{body:JSON.stringify({settingsClickToVisibleMs:settingsMs,editorReleaseToReadyMs:Date.now()-editorStart,note:'Local single sample; editor request intentionally held; not a before/after speed claim.'}),contentType:'application/json'})
})

test('column metadata and disclosures retain clear hierarchy without range clutter',async({page})=>{
  const drawer=await openSettings(page)
  await expect(drawer.getByText('勾选仅用于复制文字样式',{exact:true})).toHaveCount(0)
  await expect(drawer.locator('.bt-settings-column-status')).toHaveText('显示中')
  const headers=drawer.locator('.bt-settings-disclosure__heading')
  expect(await headers.evaluateAll(elements=>elements.every(el=>el.lastElementChild?.classList.contains('bt-settings-disclosure__toggle')))).toBe(true)
  const width=drawer.getByRole('spinbutton',{name:'列宽（px）',exact:true})
  await expect(width).toHaveAttribute('min',/\d+/)
  await expect(width).toHaveAttribute('max',/\d+/)
  await expect(width.locator('..').locator('..').locator('.bt-settings-range__caption')).toHaveCount(0)
  await drawer.getByRole('tab',{name:'操作按钮',exact:true}).click()
  expect((await drawer.locator('.bt-action-setting').first().boundingBox())!.height).toBeLessThanOrEqual(46)
  await expect(drawer.locator('.bt-action-config>.bt-tool-config__heading')).toContainText('按钮名称')
})


test('latest settings target wins while its first module request is pending',async({page})=>{
  let release!:()=>void
  const held=new Promise<void>(resolve=>{release=resolve})
  const module=/\/ColumnSettings(?:\.vue(?:\?|$)|-[^/]+\.js$)/
  await page.route(module,async route=>{await held;await route.continue()})
  await page.goto('/')
  const request=page.waitForRequest(module)
  await page.getByRole('button',{name:'列设置',exact:true}).click();await request
  await page.getByRole('button',{name:'表格设置',exact:true}).click()
  await page.getByRole('button',{name:'排序规则',exact:true}).click()
  release()
  const drawer=page.getByTestId('settings-drawer')
  await expect(drawer).toBeVisible()
  await expect(drawer.getByRole('tab',{name:'排序规则',exact:true})).toHaveAttribute('aria-selected','true')
  await expect(page.locator('.bt-column-popup')).toHaveCount(0)
})


// Deliberately failed resource: allow only that console message, while retaining
// pageerror and all other console-error checks for this recovery scenario.
networkTest('failed template module preserves settings drafts and gives a working refresh recovery',async({page})=>{
  const module=/\/RichEditor(?:\.vue(?:\?|$)|-[^/]+\.js$)/
  const errors:string[]=[];let failures=0
  page.on('pageerror',error=>errors.push(error.message))
  page.on('console',message=>{
    if(message.type()!=='error')return
    if(module.test(message.location().url)&&message.text().includes('net::ERR_FAILED')){failures++;return}
    errors.push(message.text())
  })
  await page.route(module,route=>route.abort('failed'))
  await page.goto('/')
  await page.getByRole('button',{name:'表格设置',exact:true}).click()
  const drawer=page.getByTestId('settings-drawer')
  await drawer.getByRole('textbox',{name:'显示名称',exact:true}).fill('首开恢复验证')
  await drawer.getByRole('button',{name:'编辑模板',exact:true}).click()
  const dialog=page.getByRole('dialog',{name:'编辑列显示模板',exact:true})
  await expect(dialog.getByRole('status')).toContainText('保存其他修改后刷新页面')
  await expect(dialog.getByRole('button',{name:'使用模板',exact:true})).toBeDisabled()
  await dialog.getByRole('button',{name:'关闭',exact:true}).click()
  await expect(drawer.getByRole('textbox',{name:'显示名称',exact:true})).toHaveValue('首开恢复验证')
  await drawer.getByRole('button',{name:'应用',exact:true}).click()
  await page.unroute(module);await page.reload()
  await page.getByRole('button',{name:'表格设置',exact:true}).click()
  await expect(drawer.getByRole('textbox',{name:'显示名称',exact:true})).toHaveValue('首开恢复验证')
  await drawer.getByRole('button',{name:'编辑模板',exact:true}).click()
  await expect(dialog.getByRole('textbox',{name:'列显示模板',exact:true})).toBeVisible()
  expect(failures).toBe(1);expect(errors).toEqual([])
})
