import {openSettingsSections} from './settings-helpers'
import {test, expect} from './runtime'

test('rich notes use native text input, formatting, undo and persisted ops', async ({page}) => {
  await page.goto('/')
  await page.getByRole('button', {name: '新增报价', exact: true}).click()
  const quotation = page.getByRole('dialog', {name: '新增报价', exact: true})
  await quotation.getByRole('button', {name: '富文本编辑', exact: true}).click()
  const dialog = page.getByRole('dialog', {name: '编辑备注', exact: true})
  const editor = dialog.getByRole('textbox', {name: '备注内容', exact: true})
  await expect(editor).toHaveClass(/ProseMirror/)
  await dialog.getByRole('button', {name: '粗体', exact: true}).click()
  await editor.click()
  await page.keyboard.insertText('中文备注😊')
  await expect(editor.locator('strong')).toHaveText('中文备注😊')
  await expect(dialog.locator('footer').first()).toContainText('5 / 1000')
  await editor.press('Control+z')
  await expect(editor).toHaveText('')
  await editor.press('Control+y')
  await expect(editor.locator('strong')).toHaveText('中文备注😊')
  await dialog.getByRole('button', {name: '保存', exact: true}).click()
  await quotation.getByRole('textbox', {name: '项目名称', exact: true}).fill('Tiptap 备注验收')
  await quotation.getByRole('combobox', {name: '客户', exact: true}).fill('编辑器验收客户')
  await quotation.getByRole('combobox', {name: '大区', exact: true}).selectOption('华东')
  await quotation.getByRole('textbox', {name: '含税金额（元）', exact: true}).fill('123')
  await quotation.getByRole('button', {name: '保存报价', exact: true}).click()
  await expect(quotation).toHaveCount(0)
  await page.reload()
  const row = page.locator('.vxe-table--main-wrapper .vxe-body--row').filter({hasText: 'Tiptap 备注验收'})
  const id = await row.getAttribute('rowid')
  await page.locator(`.vxe-body--row[rowid="${id}"]`).getByRole('button', {name: '查看', exact: true}).click()
  const details = page.getByRole('dialog', {name: '报价详情', exact: true})
  await expect(details.locator('.q-record-notes strong')).toHaveText('中文备注😊')
  const stored = await page.evaluate(() => {
    const data: {rows: {name: string; notesRich?: {ops: {insert: string; attributes?: {bold?: boolean}}[]}}[]} = JSON.parse(localStorage.getItem('business-table.quotation-demo.data.v1') ?? '{}')
    return data.rows.find(record => record.name === 'Tiptap 备注验收')?.notesRich
  })
  expect(stored?.ops).toContainEqual({insert: '中文备注😊', attributes: {bold: true}})
  expect(stored).not.toHaveProperty('type')
})

test('template fields stay atomic and survive save and reopen', async ({page}) => {
  await page.goto('/')
  await page.getByRole('button', {name: '表格设置', exact: true}).click()
  const drawer = page.getByTestId('settings-drawer')
  await drawer.getByRole('button', {name: '编辑列 项目名称 / 客户', exact: true}).click()
  await openSettingsSections(page,'富文本显示模板')
  await drawer.getByRole('button', {name: '编辑模板', exact: true}).click()
  let dialog = page.getByRole('dialog', {name: '编辑列显示模板', exact: true})
  let editor = dialog.getByRole('textbox', {name: '列显示模板', exact: true})
  await editor.click()
  await editor.press('Control+a')
  await editor.press('Backspace')
  await dialog.getByRole('combobox', {name: '插入字段', exact: true}).selectOption('name')
  await expect(editor.locator('[data-bt-field="name"]')).toHaveAttribute('contenteditable', 'false')
  await dialog.getByRole('button', {name: '使用模板', exact: true}).click()
  await openSettingsSections(page,'富文本显示模板')
  await drawer.getByRole('button', {name: '编辑模板', exact: true}).click()
  dialog = page.getByRole('dialog', {name: '编辑列显示模板', exact: true})
  editor = dialog.getByRole('textbox', {name: '列显示模板', exact: true})
  await editor.click()
  await editor.press('Control+End')
  await editor.press('Backspace')
  await expect(editor.locator('[data-bt-field="name"]')).toHaveCount(0)
  await editor.press('Control+z')
  await expect(editor.locator('[data-bt-field="name"]')).toHaveCount(1)
  await dialog.getByRole('button', {name: '使用模板', exact: true}).click()
  await openSettingsSections(page,'富文本显示模板')
  await drawer.getByRole('button', {name: '编辑模板', exact: true}).click()
  dialog = page.getByRole('dialog', {name: '编辑列显示模板', exact: true})
  await expect(dialog.locator('[data-bt-field="name"]')).toHaveCount(1)
  await expect(dialog.getByRole('button', {name: '链接', exact: true})).toHaveCount(0)
})

test('rich editor fits a narrow screen and sanitizes pasted HTML before editing', async ({page}) => {
  await page.setViewportSize({width: 390, height: 844})
  await page.goto('/')
  await page.getByRole('button', {name: '新增报价', exact: true}).click()
  await page.getByRole('dialog', {name: '新增报价', exact: true}).getByRole('button', {name: '富文本编辑', exact: true}).click()
  const dialog = page.getByRole('dialog', {name: '编辑备注', exact: true})
  const editor = dialog.getByRole('textbox', {name: '备注内容', exact: true})
  await editor.click()
  await editor.evaluate(element => {
    const clipboardData = new DataTransfer()
    clipboardData.setData('text/html', '<p><strong>安全粘贴</strong><script>throw new Error("bad paste")</script><img src="invalid" onerror="alert(1)"><a href="javascript:alert(1)">文本</a></p>')
    element.dispatchEvent(new ClipboardEvent('paste', {clipboardData, bubbles: true, cancelable: true}))
  })
  await expect(editor).toHaveText('安全粘贴文本')
  await expect(editor.locator('strong')).toHaveText('安全粘贴')
  await expect(editor.locator('script,img,a')).toHaveCount(0)
  const box = await dialog.boundingBox()
  expect(box).not.toBeNull()
  expect(box!.x).toBeGreaterThanOrEqual(0)
  expect(box!.x + box!.width).toBeLessThanOrEqual(391)
  expect(await dialog.locator('.bt-rich-editor').evaluate(element => element.scrollWidth - element.clientWidth)).toBeLessThanOrEqual(1)
})
