import { test, expect } from './runtime'

test('registered Demo tools are editable and saved layout controls the real toolbar after reload', async ({ page }) => {
  await page.goto('/')
  await expect(page.locator('[data-business-table]')).toContainText('Q20260914-0181')
  await page.getByTestId('table-settings').click()
  const drawer = page.getByTestId('settings-drawer')
  await drawer.getByRole('button', { name: '工具栏', exact: true }).click()
  await expect(drawer).not.toContainText('当前区域没有注册工具')
  await drawer.getByRole('textbox', { name: '刷新工具名称', exact: true }).fill('重新加载报价')
  await drawer.getByRole('combobox', { name: '刷新工具位置', exact: true }).selectOption('more')
  await drawer.getByRole('combobox', { name: '模板下载工具位置', exact: true }).selectOption('hidden')
  await drawer.getByRole('button', { name: '应用', exact: true }).click()
  await expect(drawer).toHaveCount(0)
  await expect(page.getByRole('button', { name: '模板下载', exact: true })).toHaveCount(0)
  await expect(page.getByTitle('刷新', { exact: true })).toHaveCount(0)
  await page.getByRole('button', { name: '更多表格工具', exact: true }).click()
  await page.getByRole('menuitem', { name: '重新加载报价', exact: true }).click()
  await expect(page.getByRole('menu', { name: '更多表格工具', exact: true })).toHaveCount(0)
  await page.reload()
  await expect(page.locator('[data-business-table]')).toContainText('Q20260914-0181')
  await expect(page.getByRole('button', { name: '模板下载', exact: true })).toHaveCount(0)
  await page.getByRole('button', { name: '更多表格工具', exact: true }).click()
  await expect(page.getByRole('menuitem', { name: '重新加载报价', exact: true })).toBeEnabled()
})

test('Demo explicitly enables column rule editors including mapping, template and trial', async ({ page }) => {
  await page.goto('/')
  await page.getByTestId('table-settings').click()
  const drawer = page.getByTestId('settings-drawer')
  await drawer.getByRole('button', { name: '编辑列 项目名称 / 客户', exact: true }).click()
  for (const label of ['基本', '筛选', '映射', '模板', '试算']) {
    await expect(drawer.locator('[aria-label="列设置内容"]').getByRole('button', { name: label, exact: true })).toBeEnabled()
  }
  await expect(drawer.getByRole('checkbox', { name: '启用值映射', exact: true })).toBeEnabled()
  await expect(drawer.getByRole('button', { name: '编辑模板', exact: true })).toBeEnabled()
})

for (const width of [320, 390]) {
  test(`fixed tools remain direct and responsive More menus stay in the viewport at ${width}px`, async ({ page }) => {
    await page.goto('/')
    await page.getByTestId('table-settings').click()
    const drawer = page.getByTestId('settings-drawer')
    await drawer.getByRole('button', { name: '工具栏', exact: true }).click()
    await drawer.getByRole('checkbox', { name: '固定工具 刷新', exact: true }).check()
    await drawer.getByRole('button', { name: '应用', exact: true }).click()
    await page.setViewportSize({ width, height: 700 })
    await expect(page.locator('.bt-tool-item[data-tool-id="reload"] button')).toBeVisible()
    await expect(page.locator('.bt-tool-item[data-tool-id="density"]')).toHaveCount(0)
    await expect(page.getByTestId('table-settings')).toBeVisible()
    for (const label of ['更多页面操作', '更多表格工具']) {
      await page.getByRole('button', { name: label, exact: true }).click()
      const popup = page.getByRole('menu', { name: label, exact: true })
      await expect(popup).toBeInViewport({ ratio: 1 })
      const box = await popup.boundingBox()
      expect(box!.x).toBeGreaterThanOrEqual(0)
      expect(box!.x + box!.width).toBeLessThanOrEqual(width)
      expect(box!.y + box!.height).toBeLessThanOrEqual(700)
      await page.keyboard.press('Escape')
    }
    await page.getByRole('button', { name: '更多表格工具', exact: true }).click()
    await page.getByRole('menuitem', { name: '行高密度', exact: true }).click()
    await expect(page.getByRole('menu', { name: '行高密度', exact: true })).toBeInViewport({ ratio: 1 })
    await page.getByRole('menuitemradio', { name: '紧凑', exact: true }).click()
    await expect(page.locator('[data-business-table]')).toHaveClass(/bt--compact/)
    await page.keyboard.press('Escape')
    await page.getByRole('button', { name: '更多表格工具', exact: true }).click()
    await page.getByRole('menuitem', { name: '排序规则', exact: true }).click()
    const sortDialog = page.getByRole('dialog', { name: '排序规则', exact: true })
    await sortDialog.getByRole('combobox').first().focus()
    await page.keyboard.press('Escape')
    await expect(sortDialog).toHaveCount(0)
    await expect(page.getByRole('menu', { name: '更多表格工具', exact: true })).toBeVisible()
    await page.keyboard.press('Escape')
    await page.setViewportSize({ width: 1280, height: 900 })
    await expect(page.locator('.bt-tool-item[data-tool-id="density"]')).toBeVisible()
    await page.reload()
    await page.setViewportSize({ width, height: 700 })
    await expect(page.locator('.bt-tool-item[data-tool-id="reload"] button')).toBeVisible()
    await expect(page.locator('.bt-tool-item[data-tool-id="density"]')).toHaveCount(0)
  })
}
