import {afterEach,expect,it,vi} from 'vitest'
import {defineComponent,nextTick,reactive} from 'vue'
import {flushPromises,mount,type VueWrapper} from '@vue/test-utils'
import {useTableRuntime,type TableRuntime,type TableRuntimeInput} from '../src/runtime/useTableRuntime'
import type {Query} from '../src/types'
const wrappers:VueWrapper[]=[]
afterEach(()=>{wrappers.splice(0).forEach(w=>w.unmount());vi.useRealTimers()})
async function create(extra:Partial<TableRuntimeInput<{id:number;name:string}>>={}){
  let runtime!:TableRuntime<{id:number;name:string}>
  const input=reactive({columns:[{id:'name',field:'name',title:'名称'}],data:[{id:1,name:'甲'},{id:2,name:'乙'}],searchDefinition:{items:[{id:'q',kind:'keyword'}]},...extra})
  const wrapper=mount(defineComponent({setup(){runtime=useTableRuntime(input);return()=>null}}))
  wrappers.push(wrapper);await flushPromises();return {runtime,wrapper,input}
}
it('keeps custom search drafts and applied queries across visibility changes with isolated instances',async()=>{
  const {runtime:a}=await create(),{runtime:b}=await create()
  const search=a.searchContext();search.setValue('q','甲');await search.submit();search.setValue('q','未提交')
  a.searchPanel.toggle()
  expect(a.searchPanel.visible.value).toBe(false)
  expect(b.searchPanel.visible.value).toBe(true)
  expect(search.getValue('q')).toBe('未提交')
  expect(a.rows.value.map(row=>row.id)).toEqual([1])
  a.searchPanel.setAdvanced(true);a.searchPanel.toggle()
  expect(a.searchPanel.advanced.value).toBe(true)
})
it('restores panel preferences while disabled search ignores persisted visibility',async()=>{
  const saved:unknown[]=[]
  const {runtime}=await create({searchPanelPersistence:{load:()=>({advanced:true,searchVisible:false}),save:(_key,value)=>{saved.push(value)}}})
  expect(runtime.searchPanel.visible.value).toBe(false)
  expect(runtime.searchPanel.advanced.value).toBe(true)
  runtime.searchPanel.show();await flushPromises()
  expect(saved).toEqual([{advanced:true,searchVisible:true}])
  const {runtime:off}=await create({searchDefinition:undefined})
  off.searchPanel.show();expect(off.searchPanel.visible.value).toBe(false)
})
it('debounces automatic search, submits immediately on command and cancels pending work on unmount',async()=>{
  const query=vi.fn(async()=>({rows:[],total:0}))
  const {runtime,wrapper}=await create({dataSource:{query},searchPanel:{autoSubmitMs:100}})
  vi.useFakeTimers();query.mockClear()
  runtime.searchContext().setValue('q','甲');await vi.advanceTimersByTimeAsync(50)
  runtime.searchContext().setValue('q','乙');await vi.advanceTimersByTimeAsync(99)
  expect(query).not.toHaveBeenCalled()
  await vi.advanceTimersByTimeAsync(1);expect(query).toHaveBeenCalledTimes(1)
  runtime.searchContext().setValue('q','丙');await runtime.searchContext().submit()
  await vi.advanceTimersByTimeAsync(150);expect(query).toHaveBeenCalledTimes(2)
  runtime.searchContext().setValue('q','丁');wrapper.unmount()
  await vi.advanceTimersByTimeAsync(150);expect(query).toHaveBeenCalledTimes(2)
})
it('automatically submits the legacy draft when the definition has no keyword item',async()=>{
  const query=vi.fn(async(_request:Query)=>({rows:[],total:0}))
  const {runtime}=await create({dataSource:{query},searchDefinition:{items:[{id:'name',kind:'text',field:'name',operator:'contains'}]},searchPanel:{autoSubmitMs:100}})
  vi.useFakeTimers();query.mockClear()
  runtime.searchContext().draft='甲'
  await vi.advanceTimersByTimeAsync(99);expect(query).not.toHaveBeenCalled()
  await vi.advanceTimersByTimeAsync(1)
  expect(query).toHaveBeenCalledTimes(1)
  expect(query.mock.calls[0]?.[0]).toMatchObject({keyword:'甲',page:1})
  expect(runtime.searchContext().pending).toBe(false)
})
it('does not activate automatic submission while search is disabled',async()=>{
  const query=vi.fn(async(_request:Query)=>({rows:[],total:0}))
  const {runtime}=await create({dataSource:{query},searchDefinition:undefined,searchPanel:{autoSubmitMs:100}})
  vi.useFakeTimers();query.mockClear()
  runtime.searchContext().draft='隐藏功能的草稿'
  await vi.advanceTimersByTimeAsync(150)
  expect(query).not.toHaveBeenCalled()
  expect(runtime.query.value.keyword).toBe('')
})
it.each(['page','reload'] as const)('retains a pending automatic search through %s without restarting its delay',async action=>{
  const query=vi.fn(async(_request:Query)=>({rows:[],total:40}))
  const {runtime}=await create({dataSource:{query},searchPanel:{autoSubmitMs:100}})
  vi.useFakeTimers();query.mockClear()
  runtime.searchContext().setValue('q','甲')
  await vi.advanceTimersByTimeAsync(50)
  if(action==='page')await runtime.goPage(2);else await runtime.reload()
  expect(query).toHaveBeenCalledTimes(1)
  expect(query.mock.calls[0]?.[0].keyword).toBe('')
  await vi.advanceTimersByTimeAsync(49);expect(query).toHaveBeenCalledTimes(1)
  await vi.advanceTimersByTimeAsync(1)
  expect(query).toHaveBeenCalledTimes(2)
  expect(query.mock.calls[1]?.[0]).toMatchObject({keyword:'甲',page:1})
  expect(runtime.searchContext().pending).toBe(false)
})
it.each(['甲','乙',''])('cancels pending automatic submission when setQuery explicitly applies keyword %j',async keyword=>{
  const query=vi.fn(async(_request:Query)=>({rows:[],total:0}))
  const {runtime}=await create({dataSource:{query},searchPanel:{autoSubmitMs:100}})
  vi.useFakeTimers();query.mockClear()
  runtime.searchContext().setValue('q','甲')
  await vi.advanceTimersByTimeAsync(50)
  await runtime.setQuery({keyword})
  expect(query).toHaveBeenCalledTimes(1)
  expect(query.mock.calls[0]?.[0].keyword).toBe(keyword)
  expect(runtime.searchContext().draft).toBe(keyword)
  await vi.advanceTimersByTimeAsync(150)
  expect(query).toHaveBeenCalledTimes(1)
  expect(runtime.searchContext().pending).toBe(false)
})
it.each(['sorts','filters'] as const)('preserves pending automatic submission when setQuery changes only %s',async field=>{
  const query=vi.fn(async(_request:Query)=>({rows:[],total:0}))
  const {runtime}=await create({columns:[{id:'name',field:'name',title:'名称',sortable:true}],dataSource:{query},searchPanel:{autoSubmitMs:100}})
  vi.useFakeTimers();query.mockClear()
  runtime.searchContext().setValue('q','甲')
  await vi.advanceTimersByTimeAsync(50)
  await runtime.setQuery(field==='sorts'?{keyword:undefined,sorts:[{field:'name',order:'desc'}]}:{filters:[{field:'name',operator:'contains',value:'乙'}]})
  expect(query).toHaveBeenCalledTimes(1)
  expect(query.mock.calls[0]?.[0].keyword).toBe('')
  await vi.advanceTimersByTimeAsync(49);expect(query).toHaveBeenCalledTimes(1)
  await vi.advanceTimersByTimeAsync(1)
  expect(query).toHaveBeenCalledTimes(2)
  expect(query.mock.calls[1]?.[0].keyword).toBe('甲')
  if(field==='sorts')expect(query.mock.calls[1]?.[0].sorts).toEqual([{field:'name',order:'desc'}])
  else expect(query.mock.calls[1]?.[0].filters).toEqual([{field:'name',operator:'contains',value:'乙'}])
  expect(runtime.searchContext().pending).toBe(false)
})
it.each(['reset','clear','view'] as const)('cancels the automatic search when %s replaces the draft',async action=>{
  const query=vi.fn(async(_request:Query)=>({rows:[],total:0}))
  const {runtime}=await create({dataSource:{query},searchPanel:{autoSubmitMs:100}})
  vi.useFakeTimers();query.mockClear()
  runtime.searchContext().setValue('q','待取消')
  if(action==='reset')await runtime.searchContext().reset()
  else if(action==='clear')await runtime.clearQuery()
  else await runtime.applyView({id:'saved',name:'已保存',keyword:'乙'})
  expect(query).toHaveBeenCalledTimes(1)
  expect(query.mock.calls[0]?.[0].keyword).toBe(action==='view'?'乙':'')
  await vi.advanceTimersByTimeAsync(150)
  expect(query).toHaveBeenCalledTimes(1)
  expect(runtime.searchContext().pending).toBe(false)
})
it('discards the pending automatic search when the owning table changes',async()=>{
  const query=vi.fn(async(_request:Query)=>({rows:[],total:0}))
  const {runtime,input}=await create({tableKey:'first',dataSource:{query},searchPanel:{autoSubmitMs:100}})
  vi.useFakeTimers();query.mockClear()
  runtime.searchContext().setValue('q','前一张表的草稿')
  input.tableKey='second';await nextTick()
  expect(query).toHaveBeenCalledTimes(1)
  expect(query.mock.calls[0]?.[0].keyword).toBe('')
  await vi.advanceTimersByTimeAsync(150)
  expect(query).toHaveBeenCalledTimes(1)
  expect(runtime.searchContext().pending).toBe(false)
})
it('automatically submits a fresh draft after switching table identity',async()=>{
  const query=vi.fn(async(_request:Query)=>({rows:[],total:0}))
  const {runtime,input}=await create({tableKey:'first',dataSource:{query},searchPanel:{autoSubmitMs:100}})
  expect(runtime.searchContext().pending).toBe(false)
  vi.useFakeTimers()
  input.tableKey='second';await nextTick();query.mockClear()
  runtime.searchContext().setValue('q','新表的草稿')
  expect(runtime.searchContext().pending).toBe(true)
  await vi.advanceTimersByTimeAsync(100)
  expect(query).toHaveBeenCalledTimes(1)
  expect(query.mock.calls[0]?.[0].keyword).toBe('新表的草稿')
  expect(runtime.searchContext().pending).toBe(false)
})
